package LanguageStudySystem.JavaEngStuSystem;

import java.io.*;
import java.util.*;

/**
 * 英语等级考试词库生成器 (扩展版)
 * CET4(~450词) / CET6(~400词) / IELTS(~400词) / TOEFL(~400词)  共约1650词
 * 格式兼容日文系统 JLPT 词库
 */
public class EngLevelGenerator {

    static final String SRC_DIR =
        "D:/长江大学计算机实验室/计算机实验室文件/java/LanguageStudySystem/JavaEngStuSystem/LevelWords/SortedLevel/";
    static final String WORK_DIR = "D:/EngStudy/LevelWords/SortedLevel/";

    // ══════════════════ CET-4 词库 (~450词) ══════════════════
    static final String[][] CET4 = {
        {"abandon","v. 放弃；抛弃"},{"ability","n. 能力；才能"},{"abnormal","adj. 不正常的"},
        {"aboard","adv./prep. 在船上/车上"},{"abroad","adv. 在国外"},{"absence","n. 缺席；缺乏"},
        {"absolute","adj. 绝对的；完全的"},{"absorb","v. 吸收；吸引"},{"abstract","adj. 抽象的 n. 摘要"},
        {"abundant","adj. 丰富的；充裕的"},{"abuse","n./v. 滥用；虐待"},{"academic","adj. 学术的"},
        {"accelerate","v. 加速；促进"},{"accent","n. 口音；重音"},{"access","n. 进入；通道 v. 访问"},
        {"accommodate","v. 容纳；提供住宿"},{"accompany","v. 陪伴；伴随"},{"accomplish","v. 完成；实现"},
        {"account","n. 账户；说明 v. 解释"},{"accumulate","v. 积累；积聚"},{"accurate","adj. 准确的"},
        {"accuse","v. 指责；控告"},{"achieve","v. 达到；取得"},{"acknowledge","v. 承认；确认"},
        {"acquire","v. 获得；学到"},{"adapt","v. 适应；改编"},{"addition","n. 增加；加法"},
        {"adequate","adj. 足够的；适当的"},{"adjust","v. 调整；适应"},{"administration","n. 管理；行政"},
        {"admire","v. 钦佩；赞赏"},{"admission","n. 准许进入；承认"},{"adopt","v. 采用；收养"},
        {"advance","n./v. 前进；进步"},{"advantage","n. 优势；有利条件"},{"advertise","v. 做广告"},
        {"advocate","v. 提倡 n. 倡导者"},{"affair","n. 事务；事件"},{"affect","v. 影响；感动"},
        {"afford","v. 负担得起"},{"aggressive","adj. 侵略的；好斗的"},{"agreement","n. 协议；一致"},
        {"aid","n./v. 帮助；援助"},{"alarm","n. 警报；闹钟"},{"alert","adj. 警觉的 v. 警告"},
        {"allocate","v. 分配；拨出"},{"allowance","n. 津贴；零用钱"},{"alter","v. 改变；修改"},
        {"alternative","n. 替代方案 adj. 替代的"},{"amateur","n. 业余爱好者"},{"ambition","n. 雄心；抱负"},
        {"amount","n. 数量；总额"},{"amuse","v. 使娱乐；逗笑"},{"analyze","v. 分析；解析"},
        {"ancestor","n. 祖先；祖宗"},{"angle","n. 角度；观点"},{"anniversary","n. 周年纪念日"},
        {"announce","v. 宣布；通告"},{"annual","adj. 每年的 n. 年刊"},{"anticipate","v. 预期；期望"},
        {"anxiety","n. 焦虑；忧虑"},{"apparent","adj. 明显的；表面上的"},{"appeal","n./v. 呼吁；吸引"},
        {"appetite","n. 食欲；胃口"},{"appliance","n. 电器；器具"},{"application","n. 申请；应用"},
        {"apply","v. 申请；适用"},{"appoint","v. 任命；指定"},{"appreciate","v. 欣赏；感激"},
        {"approach","v. 接近 n. 方法"},{"appropriate","adj. 适当的 v. 占用"},{"approve","v. 批准；赞成"},
        {"argue","v. 争论；辩论"},{"arise","v. 出现；产生"},{"arrange","v. 安排；整理"},
        {"arrest","n./v. 逮捕；拘留"},{"artificial","adj. 人工的；人造的"},{"aspect","n. 方面；外貌"},
        {"assemble","v. 集合；组装"},{"assess","v. 评估；评定"},{"asset","n. 资产；优点"},
        {"assign","v. 分配；指派"},{"assist","v. 帮助；协助"},{"associate","v. 联系 n. 同事"},
        {"assume","v. 假定；承担"},{"atmosphere","n. 气氛；大气"},{"attach","v. 附上；连接"},
        {"attain","v. 达到；获得"},{"attempt","n./v. 尝试；企图"},{"attend","v. 参加；出席"},
        {"attitude","n. 态度；看法"},{"attract","v. 吸引；引起"},{"attribute","v. 归因于 n. 属性"},
        {"audience","n. 观众；听众"},{"authority","n. 权威；当局"},{"automatic","adj. 自动的"},
        {"available","adj. 可用的；有效的"},{"avenue","n. 大街；途径"},{"avoid","v. 避免；回避"},
        {"award","n. 奖品 v. 授予"},{"aware","adj. 意识到的"},{"background","n. 背景"},
        {"balance","n. 平衡 v. 使平衡"},{"ban","v. 禁止 n. 禁令"},{"barrier","n. 障碍；屏障"},
        {"basis","n. 基础；根据"},{"battle","n. 战斗 v. 斗争"},{"behalf","n. 代表；利益"},
        {"behave","v. 表现；行为"},{"behavior","n. 行为；举止"},{"belief","n. 信念；信仰"},
        {"benefit","n. 利益 v. 有益于"},{"bet","n./v. 打赌"},{"beyond","prep. 超越"},
        {"blame","v. 责备 n. 责任"},{"blank","adj. 空白的 n. 空白"},{"bond","n. 纽带；债券"},
        {"boom","n. 繁荣 v. 激增"},{"border","n. 边界；边境"},{"bother","v. 打扰；烦恼"},
        {"bound","adj. 必定的 v. 跳跃"},{"brand","n. 品牌；商标"},{"breath","n. 呼吸"},
        {"brief","adj. 简短的 n. 摘要"},{"budget","n. 预算 v. 编预算"},{"burden","n. 负担 v. 使负重"},
        {"burst","v. 爆发；破裂"},{"campaign","n. 运动；战役"},{"campus","n. 校园"},
        {"cancel","v. 取消；撤销"},{"candidate","n. 候选人"},{"capacity","n. 能力；容量"},
        {"capture","v. 捕获；俘获"},{"career","n. 职业；生涯"},{"category","n. 类别；种类"},
        {"cease","v. 停止；终止"},{"challenge","n./v. 挑战"},{"channel","n. 频道；渠道"},
        {"chapter","n. 章；回"},{"characteristic","n. 特征 adj. 特有的"},{"charity","n. 慈善；施舍"},
        {"chemical","adj. 化学的 n. 化学品"},{"chief","adj. 主要的 n. 首领"},{"circumstance","n. 环境；情况"},
        {"civil","adj. 公民的；文明的"},{"claim","n./v. 声称；要求"},{"classic","adj. 经典的"},
        {"climate","n. 气候；风气"},{"colleague","n. 同事；同僚"},{"combine","v. 结合；联合"},
        {"command","n./v. 命令；指挥"},{"comment","n./v. 评论；意见"},{"commerce","n. 商业；贸易"},
        {"commission","n. 委员会；佣金 v. 委托"},{"commit","v. 犯（罪）；承诺"},{"committee","n. 委员会"},
        {"communicate","v. 交流；沟通"},{"community","n. 社区；团体"},{"companion","n. 同伴；伴侣"},
        {"compare","v. 比较；对比"},{"compensate","v. 补偿；赔偿"},{"compete","v. 竞争；比赛"},
        {"complain","v. 抱怨；投诉"},{"complex","adj. 复杂的 n. 综合体"},{"component","n. 组成部分"},
        {"compose","v. 组成；创作"},{"concentrate","v. 集中；浓缩"},{"concept","n. 概念；观念"},
        {"concern","n./v. 关心；担忧"},{"conclude","v. 总结；结束"},{"conduct","v. 进行 n. 行为"},
        {"conference","n. 会议；讨论会"},{"confidence","n. 信心；信任"},{"confirm","v. 确认；证实"},
        {"conflict","n. 冲突 v. 抵触"},{"confuse","v. 使困惑；混淆"},{"congress","n. 国会；大会"},
        {"connect","v. 连接；联系"},{"conscious","adj. 有意识的"},{"consequence","n. 结果；后果"},
        {"conservative","adj. 保守的 n. 保守派"},{"consider","v. 考虑；认为"},{"consist","v. 由…组成；在于"},
        {"constant","adj. 不变的；持续的"},{"constitute","v. 构成；组成"},{"construct","v. 建造；构建"},
        {"consume","v. 消费；消耗"},{"contact","n./v. 接触；联系"},{"contain","v. 包含；容纳"},
        {"contemporary","adj. 当代的"},{"content","n. 内容 adj. 满足的"},{"contest","n. 比赛 v. 争辩"},
        {"context","n. 背景；上下文"},{"contract","n. 合同 v. 收缩"},{"contrast","n./v. 对比；对照"},
        {"contribute","v. 贡献；捐献"},{"controversial","adj. 有争议的"},{"convenient","adj. 方便的"},
        {"convention","n. 惯例；大会"},{"convince","v. 说服；使确信"},{"cooperate","v. 合作；协作"},
        {"corporation","n. 公司；企业"},{"correspond","v. 通信；对应"},{"council","n. 委员会；理事会"},
        {"county","n. 县；郡"},{"crash","n./v. 碰撞；崩溃"},{"create","v. 创造；创建"},
        {"credit","n. 信用；学分 v. 归功于"},{"criminal","adj. 犯罪的 n. 罪犯"},{"crisis","n. 危机"},
        {"critical","adj. 批评的；关键的"},{"cultivate","v. 培养；耕种"},{"culture","n. 文化；教养"},
        {"current","adj. 当前的 n. 水流"},{"cycle","n. 循环；周期"},{"damage","n./v. 损害；毁坏"},
        {"debate","n./v. 辩论；争论"},{"decade","n. 十年"},{"decline","n./v. 下降；衰退"},
        {"defense","n. 防御；辩护"},{"define","v. 定义；界定"},{"definite","adj. 明确的；肯定的"},
        {"deliver","v. 递送；发表"},{"demand","n./v. 要求；需求"},{"demonstrate","v. 证明；示范"},
        {"deny","v. 否认；拒绝"},{"depart","v. 离开；出发"},{"dependent","adj. 依赖的；取决于"},
        {"deposit","n./v. 存款；押金"},{"depress","v. 使沮丧；压低"},{"derive","v. 源自；获得"},
        {"deserve","v. 值得；应得"},{"desire","n./v. 渴望；欲望"},{"desperate","adj. 绝望的；拼命的"},
        {"destination","n. 目的地"},{"determine","v. 决定；确定"},{"device","n. 设备；装置"},
        {"diet","n. 饮食；节食"},{"differ","v. 不同；相异"},{"digital","adj. 数字的"},
        {"discipline","n. 纪律；学科"},{"discount","n. 折扣 v. 不考虑"},{"display","n./v. 展示；显示"},
        {"dispose","v. 处理；安排"},{"distinguish","v. 区分；辨别"},{"distribute","v. 分配；分发"},
        {"domestic","adj. 国内的；家庭的"},{"draft","n. 草稿 v. 起草"},{"dramatic","adj. 戏剧性的"},
        {"economy","n. 经济；节约"},{"edition","n. 版本；版次"},{"efficient","adj. 高效的"},
        {"elaborate","adj. 精心制作的 v. 详细阐述"},{"election","n. 选举"},{"element","n. 元素；要素"},
        {"eliminate","v. 消除；淘汰"},{"embrace","v. 拥抱；包含"},{"emerge","v. 出现；浮现"},
        {"emotion","n. 情感；情绪"},{"emphasis","n. 重点；强调"},{"employ","v. 雇用；使用"},
        {"enable","v. 使能够；启用"},{"encounter","n./v. 遭遇；邂逅"},{"engage","v. 从事；订婚"},
        {"enormous","adj. 巨大的；庞大的"},{"ensure","v. 确保；保证"},{"enterprise","n. 企业；事业"},
        {"enthusiasm","n. 热情；热衷"},{"environment","n. 环境"},{"equivalent","adj. 等价的 n. 等价物"},
        {"essential","adj. 必要的；本质的"},{"establish","v. 建立；确立"},{"estate","n. 房地产；财产"},
        {"evaluate","v. 评估；评价"},{"eventually","adv. 最终；终于"},{"evidence","n. 证据；迹象"},
        {"evolve","v. 进化；发展"},{"exaggerate","v. 夸大；夸张"},{"exceed","v. 超过；超越"},
        {"exception","n. 例外；除外"},{"excess","n. 过度 adj. 过量的"},{"exchange","n./v. 交换；兑换"},
        {"exclude","v. 排除；排斥"},{"execute","v. 执行；处决"},{"exhibit","n./v. 展览；展示"},
        {"expand","v. 扩张；扩展"},{"expense","n. 花费；代价"},{"export","n./v. 出口；输出"},
        {"expose","v. 暴露；揭露"},{"extend","v. 延伸；扩展"},{"extensive","adj. 广泛的；大量的"},
        {"external","adj. 外部的；外面的"},{"extraordinary","adj. 非凡的；特别的"},
        {"extreme","adj. 极端的 n. 极端"},{"facility","n. 设施；便利"},{"factor","n. 因素；因子"},
        {"faculty","n. 能力；全体教员"},{"fashion","n. 时尚；方式"},{"fatal","adj. 致命的"},
        {"fate","n. 命运；宿命"},{"feature","n. 特征 v. 以…为特色"},{"federal","adj. 联邦的"},
        {"finance","n. 金融；财政 v. 资助"},{"focus","n./v. 集中；焦点"},{"forbid","v. 禁止；不许"},
        {"forecast","n./v. 预测；预报"},{"formal","adj. 正式的；形式上的"},{"format","n. 格式 v. 格式化"},
        {"former","adj. 从前的 n. 前者"},{"formula","n. 公式；配方"},{"foundation","n. 基础；基金会"},
        {"frank","adj. 坦白的；直率的"},{"frequency","n. 频率；频繁"},{"fulfill","v. 实现；履行"},
        {"function","n. 功能；函数 v. 运行"},{"fundamental","adj. 基本的 n. 基础"},{"genius","n. 天才"},
        {"genuine","adj. 真正的；真诚的"},{"globe","n. 地球；球体"},{"gradual","adj. 逐渐的"},
        {"guarantee","n./v. 保证；担保"},{"guideline","n. 指导方针"},{"highlight","v. 强调 n. 亮点"},
        {"horror","n. 恐怖；惊骇"},{"hostile","adj. 敌对的；怀敌意的"},{"household","n. 家庭 adj. 家用的"},
        {"humble","adj. 谦逊的；卑微的"},{"identify","v. 识别；鉴定"},{"illegal","adj. 非法的"},
        {"illustrate","v. 说明；举例"},{"image","n. 形象；图像"},{"immigrant","n. 移民 adj. 移民的"},
        {"impact","n./v. 影响；冲击"},{"implement","v. 实施 n. 工具"},{"imply","v. 暗示；意味着"},
        {"import","n./v. 进口；输入"},{"impose","v. 强加；征税"},{"impression","n. 印象；感觉"},
        {"incident","n. 事件；事变"},{"incorporate","v. 包含；合并"},{"independent","adj. 独立的"},
        {"indicate","v. 表明；显示"},{"individual","n. 个人 adj. 个别的"},{"influence","n./v. 影响"},
        {"inform","v. 通知；告知"},{"initial","adj. 最初的 n. 首字母"},{"initiative","n. 主动性 adj. 主动的"},
        {"innocent","adj. 无罪的；天真的"},{"input","n./v. 输入"},{"insight","n. 洞察力；深刻见解"},
        {"inspect","v. 检查；视察"},{"install","v. 安装；安置"},{"instance","n. 实例；情况"},
        {"instinct","n. 本能；直觉"},{"institute","n. 学院；机构 v. 建立"},{"instrument","n. 工具；乐器"},
        {"insurance","n. 保险；保险费"},{"integrate","v. 整合；融合"},{"intellectual","adj. 智力的 n. 知识分子"},
        {"intense","adj. 强烈的；紧张的"},{"interact","v. 互动；相互作用"},{"interfere","v. 干涉；干扰"},
        {"internal","adj. 内部的；国内的"},{"interpret","v. 解释；口译"},{"interval","n. 间隔；间歇"},
        {"intimate","adj. 亲密的 v. 暗示"},{"invade","v. 入侵；侵略"},{"invest","v. 投资；投入"},
        {"investigate","v. 调查；研究"},{"involve","v. 涉及；包含"},{"isolate","v. 隔离；孤立"},
        {"issue","n. 问题；议题 v. 发布"},{"journal","n. 期刊；日志"},{"justice","n. 正义；司法"},
        {"justify","v. 证明…有理"},{"label","n. 标签 v. 标注"},{"launch","n./v. 发射；启动"},
        {"layer","n. 层；层次"},{"leisure","n. 闲暇；休闲"},{"liberal","adj. 自由的；开明的"},
        {"licence","n. 许可证；执照"},{"limit","n./v. 限制；限度"},{"link","n./v. 联系；链接"},
        {"loan","n./v. 贷款；借出"},{"locate","v. 定位；位于"},{"logical","adj. 逻辑的"},
        {"maintain","v. 维持；保养"},{"major","adj. 主要的 n. 专业"},{"manual","adj. 手工的 n. 手册"},
        {"manufacture","n./v. 制造；生产"},{"margin","n. 边缘；利润"},{"maximum","adj. 最大的 n. 最大值"},
        {"mechanism","n. 机制；机械装置"},{"medium","n. 媒介 adj. 中等的"},{"mental","adj. 精神的；心理的"},
        {"military","adj. 军事的 n. 军队"},{"minimum","adj. 最小的 n. 最小值"},{"minister","n. 部长；大臣"},
        {"minor","adj. 较小的 n. 未成年人"},{"minority","n. 少数；少数民族"},{"mission","n. 任务；使命"},
        {"modify","v. 修改；调整"},{"monitor","n./v. 监控；监视"},{"moral","adj. 道德的 n. 寓意"},
        {"motion","n. 运动；动议"},{"motivate","v. 激励；激发"},{"mystery","n. 神秘；奥秘"},
        {"navigate","v. 导航；航行"},{"negative","adj. 消极的；否定的"},{"negotiate","v. 谈判；协商"},
        {"network","n. 网络；关系网"},{"neutral","adj. 中立的；中性的"},{"normal","adj. 正常的；标准的"},
        {"notion","n. 概念；想法"},{"numerous","adj. 许多的"},{"objective","n. 目标 adj. 客观的"},
        {"obtain","v. 获得；得到"},{"obvious","adj. 明显的"},{"occasion","n. 场合；时机"},
        {"offend","v. 冒犯；触怒"},{"operate","v. 操作；经营"},{"opponent","n. 对手；反对者"},
        {"opportunity","n. 机会；时机"},{"oppose","v. 反对；对抗"},{"option","n. 选择；选项"},
        {"organ","n. 器官；机构"},{"orient","v. 使适应 n. 东方"},{"origin","n. 起源；出身"},
        {"original","adj. 原始的；独创的"},{"outcome","n. 结果；成果"},{"output","n./v. 输出；产量"},
        {"overcome","v. 克服；战胜"},{"overlook","v. 俯瞰；忽略"},{"overseas","adv. 在海外 adj. 海外的"},
        {"panel","n. 面板；专家组"},{"participate","v. 参与；参加"},{"passion","n. 激情；热情"},
        {"passive","adj. 被动的；消极的"},{"pattern","n. 模式；图案"},{"peak","n. 顶峰 adj. 最高的"},
        {"peer","n. 同龄人 v. 凝视"},{"penalty","n. 惩罚；罚款"},{"perceive","v. 感知；察觉"},
        {"performance","n. 表现；性能"},{"personnel","n. 人员；人事部门"},{"perspective","n. 视角；观点"},
        {"phenomenon","n. 现象；奇迹"},{"philosophy","n. 哲学；人生观"},{"policy","n. 政策；保险单"},
        {"polish","v. 磨光；润色"},{"portion","n. 部分；一份"},{"pose","v. 摆姿势；造成 n. 姿势"},
        {"positive","adj. 积极的；肯定的"},{"possess","v. 拥有；具有"},{"potential","adj. 潜在的 n. 潜力"},
        {"precious","adj. 珍贵的；宝贵的"},{"precise","adj. 精确的；准确的"},{"predict","v. 预测；预言"},
        {"prefer","v. 更喜欢；偏好"},{"preserve","v. 保存；保护"},{"pressure","n. 压力；压迫"},
        {"previous","adj. 先前的；以前的"},{"primary","adj. 主要的；初级的"},{"principle","n. 原则；原理"},
        {"priority","n. 优先；优先权"},{"procedure","n. 程序；步骤"},{"process","n. 过程 v. 处理"},
        {"professional","adj. 专业的 n. 专业人士"},{"profit","n. 利润 v. 受益"},{"promote","v. 促进；晋升"},
        {"proportion","n. 比例；部分"},{"prospect","n. 前景；可能性"},{"protest","n./v. 抗议；反对"},
        {"provision","n. 规定；供应"},{"psychological","adj. 心理的"},{"purchase","n./v. 购买"},
        {"pursue","v. 追求；追赶"},{"qualify","v. 使合格；限定"},{"quote","n./v. 引用；报价"},
        {"range","n. 范围 v. 变化"},{"rank","n. 等级 v. 排名"},{"rate","n. 比率 v. 评价"},
        {"react","v. 反应；回应"},{"reasonable","adj. 合理的；通情达理的"},{"recognize","v. 认出；承认"},
        {"recommend","v. 推荐；建议"},{"recover","v. 恢复；康复"},{"recruit","n./v. 招募；招聘"},
        {"refer","v. 参考；提到"},{"reflect","v. 反映；反射"},{"reform","n./v. 改革；改良"},
        {"regulate","v. 调节；管理"},{"reject","v. 拒绝；排斥"},{"relate","v. 关联；叙述"},
        {"release","n./v. 释放；发布"},{"relevant","adj. 相关的；切题的"},{"relief","n. 减轻；救济"},
        {"rely","v. 依赖；信赖"},{"remove","v. 移除；消除"},{"replace","v. 取代；替换"},
        {"represent","v. 代表；表示"},{"reputation","n. 名声；声誉"},{"request","n./v. 请求；要求"},
        {"require","v. 需要；要求"},{"reserve","v. 保留；预订"},{"resident","n. 居民 adj. 居住的"},
        {"resign","v. 辞职；放弃"},{"resist","v. 抵抗；抗拒"},{"resolve","v. 解决；决心"},
        {"resource","n. 资源；财力"},{"respond","v. 回答；回应"},{"restore","v. 恢复；修复"},
        {"restrict","v. 限制；约束"},{"retain","v. 保持；保留"},{"retire","v. 退休；撤退"},
        {"reveal","v. 揭示；透露"},{"revenue","n. 收入；税收"},{"reverse","v. 逆转 adj. 相反的"},
        {"revolution","n. 革命；变革"},{"risk","n./v. 冒险；风险"},{"rival","n. 对手 v. 竞争"},
        {"route","n. 路线；航线"},{"routine","n. 常规 adj. 常规的"},{"ruin","n./v. 毁灭；废墟"},
        {"sacrifice","n./v. 牺牲；献祭"},{"satisfaction","n. 满足；满意"},{"scale","n. 规模；比例"},
        {"scan","v. 扫描；浏览"},{"schedule","n. 时间表 v. 安排"},{"scheme","n. 计划；方案"},
        {"scope","n. 范围；领域"},{"security","n. 安全；证券"},{"senior","adj. 高级的 n. 年长者"},
        {"session","n. 会议；学期"},{"settle","v. 解决；定居"},{"severe","adj. 严重的；严厉的"},
        {"shelter","n. 庇护所 v. 保护"},{"shift","n./v. 转变；轮班"},{"signal","n. 信号 v. 发信号"},
        {"significant","adj. 重要的；显著的"},{"similar","adj. 相似的；类似的"},{"simplify","v. 简化"},
        {"site","n. 地点；场所"},{"situation","n. 情况；形势"},{"slight","adj. 轻微的；纤细的"},
        {"source","n. 来源；出处"},{"specific","adj. 特定的；具体的"},{"stable","adj. 稳定的 n. 马厩"},
        {"staff","n. 工作人员；职员"},{"standard","n. 标准 adj. 标准的"},{"status","n. 地位；状态"},
        {"strategy","n. 战略；策略"},{"structure","n. 结构 v. 构建"},{"submit","v. 提交；服从"},
        {"sufficient","adj. 足够的；充分的"},{"summarize","v. 总结；概括"},{"superior","adj. 上级的；优越的"},
        {"supply","n./v. 供应；提供"},{"survey","n./v. 调查；测量"},{"survive","v. 幸存；存活"},
        {"suspect","v. 怀疑 n. 嫌疑人"},{"suspend","v. 暂停；悬挂"},{"sustain","v. 维持；支撑"},
        {"symbol","n. 象征；符号"},{"target","n. 目标 v. 瞄准"},{"tendency","n. 趋势；倾向"},
        {"terminal","n. 终端 adj. 末期的"},{"textile","n. 纺织品 adj. 纺织的"},{"theme","n. 主题；题目"},
        {"threat","n. 威胁；恐吓"},{"tolerance","n. 容忍；宽容"},{"trace","n. 痕迹 v. 追踪"},
        {"tradition","n. 传统；惯例"},{"transfer","n./v. 转移；调动"},{"transform","v. 改变；转换"},
        {"transport","n./v. 运输；运送"},{"treat","v. 对待；治疗 n. 款待"},{"trend","n. 趋势；潮流"},
        {"trigger","n. 扳机 v. 触发"},{"ultimate","adj. 最终的；根本的"},{"undergo","v. 经历；遭受"},
        {"undertake","v. 承担；从事"},{"unique","adj. 独特的；唯一的"},{"universal","adj. 普遍的；全体的"},
        {"urban","adj. 城市的；都市的"},{"urge","v. 催促 n. 强烈欲望"},{"valid","adj. 有效的；合理的"},
        {"variety","n. 多样；种类"},{"vehicle","n. 车辆；工具"},{"venture","n./v. 冒险；企业"},
        {"version","n. 版本；说法"},{"victim","n. 受害者；牺牲品"},{"violence","n. 暴力；猛烈"},
        {"virtual","adj. 虚拟的；实质上的"},{"virtue","n. 美德；优点"},{"visible","adj. 可见的"},
        {"vision","n. 视力；愿景"},{"visual","adj. 视觉的；可视的"},{"vital","adj. 至关重要的"},
        {"volume","n. 体积；音量"},{"voluntary","adj. 自愿的；志愿的"},{"welfare","n. 福利；幸福"},
        {"widespread","adj. 广泛的；普遍的"},{"witness","n. 证人 v. 目击"},{"yield","v. 产生 n. 产量"},
    };

    // ══════════════════ CET-6 词库 (~400词) ══════════════════
    static final String[][] CET6 = {
        {"abnormal","adj. 不正常的；异常的"},{"abolish","v. 废除；取消"},
        {"abrupt","adj. 突然的；唐突的"},{"absurd","adj. 荒谬的；可笑的"},
        {"accessory","n. 附件；配件 adj. 附属的"},{"acquaint","v. 使认识；使了解"},
        {"activate","v. 激活；启动"},{"acute","adj. 急性的；敏锐的"},
        {"adhere","v. 粘附；坚持"},{"adjacent","adj. 邻近的；毗连的"},
        {"administer","v. 管理；执行"},{"adolescent","n. 青少年 adj. 青春期的"},
        {"advent","n. 到来；出现"},{"adverse","adj. 不利的；相反的"},
        {"aerial","adj. 空中的 n. 天线"},{"aesthetic","adj. 美学的；审美的"},
        {"affiliate","v. 使附属 n. 分支机构"},{"affirm","v. 断言；确认"},
        {"afflict","v. 使痛苦；折磨"},{"aggravate","v. 加重；恶化"},
        {"aggregate","n. 合计 v. 聚集"},{"agitate","v. 搅动；煽动"},
        {"agony","n. 极大痛苦；苦恼"},{"allege","v. 断言；宣称"},
        {"alleviate","v. 减轻；缓解"},{"allocate","v. 分配；拨出"},
        {"alloy","n. 合金 v. 使成合金"},{"alternate","adj. 交替的 v. 交替"},
        {"ambiguous","adj. 含糊的；模棱两可的"},{"ambitious","adj. 有雄心的"},
        {"amend","v. 修改；修订"},{"ample","adj. 充足的；丰富的"},
        {"amplify","v. 放大；增强"},{"analogy","n. 类比；相似"},
        {"anonymous","adj. 匿名的；无名的"},{"apparatus","n. 器械；装置"},
        {"applaud","v. 鼓掌；称赞"},{"appraisal","n. 评价；评估"},
        {"appreciable","adj. 可感知的；明显的"},{"apprehension","n. 理解；忧虑"},
        {"apt","adj. 恰当的；有…倾向的"},{"array","n. 数组；排列 v. 部署"},
        {"arrogant","adj. 傲慢的；自大的"},{"articulate","v. 清晰表达 adj. 口齿伶俐的"},
        {"ascend","v. 上升；攀登"},{"ascribe","v. 把…归因于"},
        {"aspiration","n. 渴望；抱负"},{"assault","n./v. 攻击；袭击"},
        {"assert","v. 断言；坚持"},{"assimilate","v. 吸收；同化"},
        {"assurance","n. 保证；保险"},{"astronomy","n. 天文学"},
        {"attendance","n. 出席；到场"},{"attendant","n. 服务员 adj. 伴随的"},
        {"authentic","adj. 真实的；可靠的"},{"authoritative","adj. 权威的；官方的"},
        {"authorize","v. 授权；批准"},{"autonomy","n. 自治；自主权"},
        {"avail","v. 有益于 n. 效用"},{"avert","v. 避免；转移"},
        {"aviation","n. 航空；飞行"},{"baffle","v. 使困惑；难住"},
        {"bald","adj. 秃头的；单调的"},{"bankrupt","adj. 破产的 v. 使破产"},
        {"barren","adj. 贫瘠的；不育的"},{"beforehand","adv. 预先；事先"},
        {"betray","v. 背叛；泄露"},{"bewilder","v. 使迷惑；使困惑"},
        {"bias","n. 偏见 v. 使有偏见"},{"bibliography","n. 参考书目"},
        {"bizarre","adj. 奇异的；古怪的"},{"blaze","n. 火焰 v. 燃烧"},
        {"bleak","adj. 荒凉的；暗淡的"},{"bless","v. 祝福；保佑"},
        {"blunder","n. 大错 v. 犯大错"},{"bonus","n. 奖金；红利"},
        {"boycott","n./v. 联合抵制"},{"breach","n. 违反 v. 打破"},
        {"breakdown","n. 崩溃；故障"},{"bribe","n. 贿赂 v. 行贿"},
        {"brisk","adj. 轻快的；兴隆的"},{"bruise","n. 瘀伤 v. 使受伤"},
        {"brutal","adj. 残忍的；野蛮的"},{"bulletin","n. 公告；简报"},
        {"bureaucracy","n. 官僚机构"},{"cabinet","n. 内阁；橱柜"},
        {"cater","v. 提供饮食；迎合"},{"caution","n. 谨慎；警告"},
        {"census","n. 人口普查"},{"certify","v. 证明；证实"},
        {"chronic","adj. 慢性的；长期的"},{"circulation","n. 循环；发行量"},
        {"clamp","n. 夹钳 v. 夹住"},{"climax","n. 高潮；顶点"},
        {"cling","v. 紧贴；坚持"},{"coincide","v. 同时发生；一致"},
        {"collaborate","v. 合作；勾结"},{"collide","v. 碰撞；冲突"},
        {"commence","v. 开始；着手"},{"commend","v. 表扬；推荐"},
        {"commodity","n. 商品；货物"},{"commonplace","adj. 平凡的 n. 常见的事"},
        {"compatible","adj. 兼容的；合得来的"},{"compensate","v. 补偿；赔偿"},
        {"compile","v. 编译；汇编"},{"complement","v. 补充 n. 补足物"},
        {"complication","n. 复杂；并发症"},{"compliment","n. 赞美 v. 称赞"},
        {"comply","v. 遵守；顺从"},{"compulsory","adj. 强制的；必修的"},
        {"conceive","v. 构想；怀孕"},{"conception","n. 概念；构想"},
        {"concise","adj. 简洁的；简明的"},{"confer","v. 授予；商议"},
        {"confidential","adj. 机密的；保密的"},{"configuration","n. 配置；结构"},
        {"conform","v. 遵守；符合"},{"confront","v. 面对；对抗"},
        {"consecutive","adj. 连续的；连贯的"},{"consensus","n. 共识；一致意见"},
        {"consequent","adj. 随之发生的"},{"conserve","v. 保存；节约"},
        {"consolidate","v. 巩固；合并"},{"conspicuous","adj. 显眼的；明显的"},
        {"constrain","v. 限制；约束"},{"consult","v. 咨询；查阅"},
        {"contaminate","v. 污染；玷污"},{"contemplate","v. 沉思；考虑"},
        {"contend","v. 竞争；主张"},{"contradict","v. 矛盾；反驳"},
        {"contrive","v. 发明；设法做到"},{"controversy","n. 争议；争论"},
        {"convene","v. 召集；集合"},{"converge","v. 聚集；汇合"},
        {"convict","v. 定罪 n. 囚犯"},{"conviction","n. 信念；定罪"},
        {"cordial","adj. 热诚的；友好的"},{"correlate","v. 使相关联"},
        {"corrode","v. 腐蚀；侵蚀"},{"criterion","n. 标准；准则"},
        {"crucial","adj. 至关重要的"},{"cumulative","adj. 累积的"},
        {"cynical","adj. 愤世嫉俗的"},{"dazzle","v. 使目眩 n. 耀眼"},
        {"decent","adj. 体面的；正派的"},{"decisive","adj. 决定性的；果断的"},
        {"declare","v. 宣布；声明"},{"decline","v. 下降；拒绝 n. 衰退"},
        {"dedicate","v. 奉献；致力于"},{"deem","v. 认为；视为"},
        {"deficiency","n. 缺乏；不足"},{"defy","v. 违抗；挑战"},
        {"degenerate","v. 退化；堕落"},{"degrade","v. 降低；贬低"},
        {"deliberate","adj. 故意的 v. 仔细考虑"},{"denial","n. 否认；拒绝"},
        {"denote","v. 表示；意味着"},{"depict","v. 描绘；描述"},
        {"deprive","v. 剥夺；使丧失"},{"descendant","n. 后代；子孙"},
        {"descent","n. 下降；血统"},{"designate","v. 指定；任命"},
        {"despise","v. 鄙视；看不起"},{"detach","v. 分离；派遣"},
        {"detain","v. 拘留；耽搁"},{"deteriorate","v. 恶化；退化"},
        {"deviate","v. 偏离；背离"},{"diagnose","v. 诊断；判断"},
        {"diffuse","v. 扩散；传播 adj. 弥漫的"},{"dilemma","n. 困境；进退两难"},
        {"dilute","v. 稀释；冲淡"},{"diminish","v. 减少；缩小"},
        {"diploma","n. 文凭；毕业证书"},{"disastrous","adj. 灾难性的"},
        {"discern","v. 辨别；识别"},{"disclose","v. 揭露；透露"},
        {"discourse","n. 论述；话语"},{"discrepancy","n. 差异；不一致"},
        {"discrete","adj. 离散的；分离的"},{"discriminate","v. 歧视；区别"},
        {"disguise","v. 伪装 n. 伪装品"},{"dismay","n. 沮丧 v. 使惊慌"},
        {"dispatch","v. 派遣 n. 急件"},{"disperse","v. 分散；驱散"},
        {"displace","v. 取代；置换"},{"disposition","n. 性情；处置"},
        {"disregard","v. 忽视 n. 漠视"},{"disrupt","v. 扰乱；中断"},
        {"dissolve","v. 溶解；解散"},{"distort","v. 扭曲；歪曲"},
        {"distract","v. 分心；分散注意力"},{"disturbance","n. 打扰；骚乱"},
        {"diversion","n. 转移；消遣"},{"divert","v. 转移；使分心"},
        {"dominant","adj. 占优势的；支配的"},{"donate","v. 捐赠；捐献"},
        {"doom","n. 命运 v. 注定"},{"drastic","adj. 激烈的；极端的"},
        {"drought","n. 干旱"},{"dual","adj. 双重的；二元的"},
        {"dubious","adj. 可疑的；含糊的"},{"duplicate","v. 复制 n. 副本"},
        {"dwell","v. 居住；细想"},{"eccentric","adj. 古怪的 n. 怪人"},
        {"eclipse","n. 日食 v. 使黯然失色"},{"ecology","n. 生态学"},
        {"edible","adj. 可食用的"},{"ego","n. 自我；自尊"},
        {"eject","v. 驱逐；弹出"},{"elapse","v. 消逝；流逝"},
        {"elicit","v. 引出；探出"},{"eligible","adj. 有资格的；合格的"},
        {"elite","n. 精英 adj. 精英的"},{"eloquent","adj. 有口才的；雄辩的"},
        {"embark","v. 着手；上船"},{"embed","v. 嵌入；植入"},
        {"embody","v. 体现；包含"},{"empirical","adj. 经验主义的"},
        {"endeavor","n./v. 努力；尽力"},{"endow","v. 赋予；捐赠"},
        {"endurance","n. 耐力；持久力"},{"energetic","adj. 精力充沛的"},
        {"enlighten","v. 启蒙；启发"},{"enrich","v. 丰富；使充实"},
        {"enroll","v. 登记；注册"},{"ensue","v. 继而发生；随之而来"},
        {"entail","v. 需要；牵涉"},{"entity","n. 实体；存在物"},
        {"entrepreneur","n. 企业家"},{"envisage","v. 想象；设想"},
        {"epidemic","n. 流行病 adj. 流行的"},{"epoch","n. 时代；纪元"},
        {"erase","v. 擦掉；清除"},{"erosion","n. 侵蚀；腐蚀"},
        {"erroneous","adj. 错误的；不正确的"},{"erupt","v. 爆发；喷发"},
        {"essence","n. 本质；精华"},{"esteem","n./v. 尊重；尊敬"},
        {"eternal","adj. 永恒的；永久的"},{"evacuate","v. 疏散；撤离"},
        {"evaporate","v. 蒸发；消失"},{"evoke","v. 唤起；引起"},
        {"excerpt","n. 摘录；选段"},{"execution","n. 执行；处决"},
        {"exempt","v. 免除 adj. 被免除的"},{"exile","n./v. 流放；放逐"},
        {"exotic","adj. 异国情调的"},{"expedition","n. 远征；探险队"},
        {"expel","v. 驱逐；开除"},{"expire","v. 到期；失效"},
        {"explicit","adj. 明确的；直白的"},{"exquisite","adj. 精致的；细腻的"},
        {"extinct","adj. 灭绝的；熄灭的"},{"extinguish","v. 熄灭；消灭"},
        {"extract","v. 提取 n. 摘录"},{"extravagant","adj. 奢侈的；过度的"},
        {"fabricate","v. 制造；捏造"},{"facet","n. 方面；刻面"},
        {"fake","adj. 假的 n. 赝品 v. 伪造"},{"fantastic","adj. 极好的；奇异的"},
        {"feast","n. 盛宴 v. 款待"},{"feeble","adj. 虚弱的；无力的"},
        {"feminine","adj. 女性的；阴性的"},{"ferry","n. 渡轮 v. 摆渡"},
        {"finite","adj. 有限的；限定的"},{"fitting","adj. 合适的 n. 配件"},
        {"fixture","n. 固定装置"},{"flap","v. 拍打 n. 拍打声"},
        {"flare","v. 闪耀 n. 闪光"},{"flaw","n. 缺陷；瑕疵"},
        {"fling","v. 猛扔；投身于"},{"flip","v. 轻弹；翻"},
        {"fluctuate","v. 波动；涨落"},{"flush","v. 冲洗 adj. 齐平的"},
        {"flutter","v. 拍翅；飘动"},{"foam","n. 泡沫 v. 起泡"},
        {"foil","n. 箔纸 v. 挫败"},{"foremost","adj. 最重要的；首先的"},
        {"foresee","v. 预见；预知"},{"formidable","adj. 可怕的；强大的"},
        {"formulate","v. 制定；规划"},{"fort","n. 堡垒；要塞"},
        {"forthcoming","adj. 即将来临的"},{"fossil","n. 化石 adj. 化石的"},
        {"foster","v. 培养；促进"},{"fracture","n. 骨折 v. 破裂"},
        {"fragile","adj. 脆弱的；易碎的"},{"friction","n. 摩擦；冲突"},
        {"frown","v. 皱眉 n. 皱眉"},{"furious","adj. 狂怒的；激烈的"},
        {"fuse","v. 融合 n. 保险丝"},{"futile","adj. 徒劳的；无效的"},
        {"galaxy","n. 星系；银河"},{"gasp","v. 喘气 n. 喘息"},
        {"gauge","n. 量规 v. 测量"},{"generalize","v. 概括；推广"},
        {"generate","v. 产生；生成"},{"gigantic","adj. 巨大的；庞大的"},
        {"glare","v. 怒视；闪耀 n. 强光"},{"gleam","n. 微光 v. 闪烁"},
        {"glide","v. 滑行；滑翔"},{"glimpse","n. 一瞥 v. 瞥见"},
        {"glitter","v. 闪烁 n. 闪光"},{"gloomy","adj. 阴暗的；忧郁的"},
        {"gorgeous","adj. 华丽的；极好的"},{"gossip","n. 流言蜚语 v. 说闲话"},
        {"gracious","adj. 亲切的；优雅的"},{"grieve","v. 使悲伤；哀悼"},
        {"grim","adj. 严峻的；阴森的"},{"grin","v. 露齿而笑 n. 咧嘴笑"},
        {"groan","v. 呻吟 n. 呻吟声"},{"grope","v. 摸索；探索"},
        {"guardian","n. 监护人；保护者"},{"hamper","v. 妨碍；阻碍"},
        {"handicap","n. 障碍 v. 妨碍"},{"haul","v. 拖；拉 n. 拖运"},
        {"haunt","v. 萦绕；常去"},{"heal","v. 治愈；愈合"},
        {"heap","n. 堆 v. 堆积"},{"heighten","v. 提高；增强"},
        {"heritage","n. 遗产；传统"},{"hierarchy","n. 等级制度；层级"},
        {"hinder","v. 阻碍；妨碍"},{"hitherto","adv. 迄今；至今"},
        {"hoist","v. 升起 n. 起重机"},{"hollow","adj. 中空的；空洞的"},
        {"homogeneous","adj. 同质的；同类的"},{"hose","n. 软管 v. 用软管冲洗"},
        {"hospitality","n. 好客；款待"},{"hostage","n. 人质"},
        {"hover","v. 盘旋；徘徊"},{"hug","v. 拥抱 n. 拥抱"},
        {"humanity","n. 人类；人性"},{"humidity","n. 湿度；潮湿"},
        {"hurl","v. 猛投；摔"},{"hypothesis","n. 假设；假说"},
        {"hysterical","adj. 歇斯底里的"},{"identification","n. 识别；身份证明"},
        {"ideology","n. 意识形态"},{"ignite","v. 点燃；起火"},
        {"illuminate","v. 照亮；阐明"},{"illusion","n. 幻觉；错觉"},
        {"imaginative","adj. 富有想象力的"},{"immerse","v. 沉浸；使陷入"},
        {"immune","adj. 免疫的；豁免的"},{"impair","v. 损害；削弱"},
        {"impart","v. 传授；告知"},{"imperative","adj. 必要的 n. 命令"},
        {"impetus","n. 动力；推动力"},{"implicit","adj. 含蓄的；内含的"},
        {"impulse","n. 冲动；推动力"},{"inaugurate","v. 开创；举行就职典礼"},
        {"incentive","n. 激励；刺激"},{"incidentally","adv. 顺便提及；偶然"},
        {"inclusive","adj. 包含的；包容的"},{"incorporate","v. 包含；合并"},
        {"incredible","adj. 难以置信的"},{"incur","v. 招致；遭受"},
        {"indefinite","adj. 不确定的；模糊的"},{"indicative","adj. 指示的；表明的"},
        {"indignant","adj. 愤慨的；愤怒的"},{"indignation","n. 愤怒；愤慨"},
        {"indispensable","adj. 不可或缺的"},{"induce","v. 引起；诱导"},
        {"indulge","v. 放纵；沉溺"},{"infectious","adj. 传染的；有感染力的"},
        {"infer","v. 推断；推论"},{"ingenious","adj. 巧妙的；有独创性的"},
        {"inhabit","v. 居住于；栖息于"},{"inhibit","v. 抑制；禁止"},
        {"initiate","v. 开始；发起"},{"inject","v. 注射；注入"},
        {"inland","adj. 内陆的 adv. 在内陆"},{"innovation","n. 创新；革新"},
        {"innumerable","adj. 无数的；数不清的"},{"insane","adj. 疯狂的；精神错乱的"},
        {"installment","n. 分期付款；一集"},{"instantaneous","adj. 瞬间的；即时的"},
        {"instrumental","adj. 起作用的；乐器的"},{"insulate","v. 绝缘；隔离"},
        {"intact","adj. 完好无损的；完整的"},{"integral","adj. 必需的；完整的"},
        {"integrity","n. 正直；完整"},{"intelligible","adj. 可理解的；明白的"},
        {"intensify","v. 强化；加剧"},{"intent","n. 意图 adj. 专注的"},
        {"intervene","v. 干涉；介入"},{"intricate","adj. 复杂精细的"},
        {"intrinsic","adj. 固有的；内在的"},{"intuition","n. 直觉"},
        {"invalid","adj. 无效的 n. 病人"},{"invaluable","adj. 无价的；极其宝贵的"},
        {"invariably","adv. 总是；不变地"},{"inventory","n. 清单；库存"},
        {"invert","v. 倒转；颠倒"},{"irony","n. 讽刺；反语"},
        {"irrespective","adj. 不论的；无关的"},{"irrigation","n. 灌溉"},
        {"irritate","v. 刺激；激怒"},{"jerk","n. 急拉 v. 猛拉"},
        {"jeopardize","v. 危及；危害"},{"jog","v. 慢跑 n. 轻推"},
        {"junction","n. 交叉点；连接处"},{"latent","adj. 潜在的；潜伏的"},
        {"latitude","n. 纬度；自由"},{"layman","n. 外行；门外汉"},
        {"leaflet","n. 传单；小册子"},{"legend","n. 传说；传奇"},
        {"legitimate","adj. 合法的；正当的"},{"liability","n. 责任；负债"},
        {"lick","v. 舔 n. 少量"},{"likelihood","n. 可能性"},
        {"limp","v. 跛行 adj. 软弱的"},{"linear","adj. 线性的；直线的"},
        {"linger","v. 逗留；徘徊"},{"literacy","n. 读写能力；有文化"},
        {"literal","adj. 字面意思的；逐字的"},{"litter","n. 垃圾 v. 乱扔"},
        {"lobby","n. 大厅 v. 游说"},{"locomotive","n. 火车头 adj. 移动的"},
        {"lofty","adj. 崇高的；高耸的"},{"lounge","n. 休息室 v. 懒坐"},
        {"lubricate","v. 润滑；使顺畅"},{"luminous","adj. 发光的；明亮的"},
        {"lure","v. 引诱 n. 诱惑物"},{"magnify","v. 放大；夸大"},
        {"manifest","v. 表明 adj. 明显的"},{"manipulate","v. 操纵；操作"},
        {"marshal","n. 元帅 v. 整理"},{"masculine","adj. 男性的；阳性的"},
        {"massacre","n. 大屠杀 v. 屠杀"},{"mediate","v. 调解；斡旋"},
        {"medieval","adj. 中世纪的"},{"menace","n. 威胁 v. 威胁"},
        {"merge","v. 合并；融合"},{"migrate","v. 迁移；移居"},
        {"militant","adj. 好战的 n. 激进分子"},{"mingle","v. 混合；交往"},
        {"miniature","adj. 微型的 n. 微型画"},{"minimal","adj. 最小的；最低限度的"},
        {"minimize","v. 最小化；降到最低"},{"misery","n. 痛苦；悲惨"},
        {"misfortune","n. 不幸；灾祸"},{"mobilize","v. 动员；调动"},
        {"mock","v. 嘲笑 adj. 模拟的"},{"momentum","n. 动力；势头"},
        {"monopoly","n. 垄断；独占"},{"mortal","adj. 凡人的；致命的"},
        {"mortgage","n. 抵押 v. 抵押"},{"multitude","n. 大量；群众"},
        {"municipal","adj. 市政的；市的"},{"murmur","v. 低语 n. 低语声"},
        {"naive","adj. 天真的；幼稚的"},{"narrative","n. 叙述 adj. 叙事的"},
        {"nasty","adj. 恶劣的；肮脏的"},{"necessitate","v. 使成为必要"},
        {"negligible","adj. 可以忽略的；微不足道的"},{"nominate","v. 提名；任命"},
        {"nonetheless","adv. 尽管如此"},{"notable","adj. 显著的 n. 名人"},
        {"notorious","adj. 臭名昭著的"},{"nourish","v. 滋养；养育"},
        {"novelty","n. 新奇；新颖"},{"nurture","v. 培育 n. 养育"},
        {"oath","n. 誓言；诅咒"},{"obedience","n. 服从；顺从"},
        {"obligation","n. 义务；责任"},{"obscene","adj. 猥亵的；淫秽的"},
        {"obscure","adj. 模糊的 v. 使朦胧"},{"odor","n. 气味；臭味"},
        {"offspring","n. 后代；子孙"},{"opaque","adj. 不透明的；难以理解的"},
        {"oppress","v. 压迫；压制"},{"opt","v. 选择；抉择"},
        {"optimism","n. 乐观；乐观主义"},{"orbit","n. 轨道 v. 绕轨道运行"},
        {"oriental","adj. 东方的"},{"originate","v. 起源；产生"},
        {"ornament","n. 装饰品 v. 装饰"},{"outbreak","n. 爆发；突然发生"},
        {"overflow","v. 溢出 n. 泛滥"},{"overhear","v. 无意中听到"},
        {"overlap","v. 重叠 n. 重叠部分"},{"overt","adj. 公开的；明显的"},
        {"overthrow","v. 推翻 n. 推翻"},{"overwhelm","v. 压倒；淹没"},
        {"paradox","n. 矛盾；悖论"},{"paralyze","v. 使瘫痪；使无效"},
        {"pastime","n. 消遣；娱乐"},{"patent","n. 专利 adj. 专利的"},
        {"pathetic","adj. 可怜的；悲哀的"},{"patriotic","adj. 爱国的"},
        {"patrol","n./v. 巡逻；巡查"},{"pave","v. 铺路；铺设"},
        {"pearl","n. 珍珠"},{"peculiar","adj. 奇怪的；独特的"},
        {"pedestrian","n. 行人 adj. 平淡的"},{"peel","v. 剥皮 n. 果皮"},
        {"pendulum","n. 钟摆；摇摆不定"},{"pension","n. 养老金；退休金"},
        {"perception","n. 感知；理解"},{"perfume","n. 香水 v. 使散发香气"},
        {"periodic","adj. 周期性的"},{"perish","v. 死亡；毁灭"},
        {"permanent","adj. 永久的；持久的"},{"permeate","v. 渗透；弥漫"},
        {"permissible","adj. 允许的；许可的"},{"perpetual","adj. 永久的；持续的"},
        {"perplex","v. 使困惑；使复杂"},{"persistent","adj. 坚持的；持续的"},
        {"pessimistic","adj. 悲观的"},{"petition","n. 请愿书 v. 请愿"},
        {"petty","adj. 琐碎的；小气的"},{"plague","n. 瘟疫 v. 困扰"},
        {"plead","v. 恳求；辩护"},{"pledge","n. 誓言 v. 承诺"},
        {"poke","v. 戳；捅"},{"polar","adj. 极地的；完全相反的"},
        {"ponder","v. 沉思；考虑"},{"portray","v. 描绘；扮演"},
        {"precede","v. 在…之前；先于"},{"precedent","n. 先例；前例"},
        {"preclude","v. 排除；阻止"},{"predominant","adj. 占优势的；主要的"},
        {"pregnant","adj. 怀孕的；富有意义的"},{"premature","adj. 过早的；不成熟的"},
        {"premium","n. 保险费 adj. 优质的"},{"prescription","n. 处方；药方"},
        {"preside","v. 主持；掌管"},{"prestige","n. 威望；声望"},
        {"presumably","adv. 大概；可能"},{"presume","v. 推测；假定"},
        {"prevalent","adj. 普遍的；流行的"},{"prey","n. 猎物 v. 捕食"},
        {"probe","n./v. 探测；调查"},{"proceeding","n. 程序；诉讼"},
        {"proclaim","v. 宣布；宣告"},{"productive","adj. 多产的；富有成效的"},
        {"proficiency","n. 熟练；精通"},{"profound","adj. 深刻的；深邃的"},
        {"prolong","v. 延长；拉长"},{"promising","adj. 有前途的；有希望的"},
        {"prone","adj. 有…倾向的；俯卧的"},{"propaganda","n. 宣传；鼓吹"},
        {"propel","v. 推进；推动"},{"prophet","n. 先知；预言者"},
        {"prosecute","v. 起诉；控告"},{"provoke","v. 激怒；引起"},
        {"proximity","n. 接近；邻近"},{"purify","v. 净化；提纯"},
        {"pursuit","n. 追求；追赶"},{"quest","n./v. 寻求；探索"},
        {"questionnaire","n. 问卷；调查表"},{"quota","n. 配额；限额"},
        {"radiant","adj. 辐射的；容光焕发的"},{"random","adj. 随机的；任意的"},
        {"rap","n. 轻敲；说唱 v. 敲击"},{"rape","n./v. 强奸；掠夺"},
        {"rash","adj. 轻率的 n. 皮疹"},{"reassure","v. 使安心；再保证"},
        {"rebellion","n. 叛乱；反抗"},{"recession","n. 经济衰退；后退"},
        {"recipe","n. 食谱；秘诀"},{"reckon","v. 认为；计算"},
        {"reclaim","v. 回收；开垦"},{"reconcile","v. 调和；使和解"},
        {"recreation","n. 娱乐；消遣"},{"rectify","v. 纠正；矫正"},
        {"recur","v. 复发；重现"},{"redundant","adj. 多余的；冗长的"},
        {"refrain","v. 克制；避免 n. 副歌"},{"refute","v. 驳斥；反驳"},
        {"regime","n. 政权；制度"},{"rehearsal","n. 排练；预演"},
        {"reign","n. 统治 v. 统治"},{"rein","n. 缰绳 v. 控制"},
        {"rejoice","v. 欣喜；高兴"},{"relay","v. 转播 n. 接力赛"},
        {"reliance","n. 依赖；信赖"},{"remainder","n. 剩余部分；余数"},
        {"remedy","n. 补救办法 v. 补救"},{"remnant","n. 残余；剩余物"},
        {"renaissance","n. 文艺复兴；复兴"},{"repel","v. 击退；排斥"},
        {"repertoire","n. 全部节目；全部技能"},{"repression","n. 压抑；压制"},
        {"reproach","n./v. 责备；批评"},{"resemblance","n. 相似；类似"},
        {"resent","v. 怨恨；愤恨"},{"reside","v. 居住；存在"},
        {"residential","adj. 住宅的；居住的"},{"resignation","n. 辞职；顺从"},
        {"resistant","adj. 抵抗的；抗…的"},{"resolution","n. 决心；决议"},
        {"respective","adj. 各自的；分别的"},{"retort","n./v. 反驳；回嘴"},
        {"retrieve","v. 取回；检索"},{"retrospect","n. 回顾；回想"},
        {"revenge","n./v. 报复；复仇"},{"revive","v. 复兴；苏醒"},
        {"revolve","v. 旋转；围绕"},{"rigorous","adj. 严格的；严密的"},
        {"ritual","n. 仪式 adj. 仪式的"},{"robust","adj. 强健的；坚固的"},
        {"rot","v. 腐烂 n. 腐烂"},{"rupture","n. 破裂 v. 使破裂"},
        {"sacred","adj. 神圣的；宗教的"},{"safeguard","n./v. 保护；防护"},
        {"salute","n./v. 敬礼；致敬"},{"sanction","n. 制裁 v. 批准"},
        {"saturate","v. 饱和；浸透"},{"savage","adj. 野蛮的 n. 野蛮人"},
        {"scandal","n. 丑闻；诽谤"},{"scorn","n./v. 轻蔑；蔑视"},
        {"scrap","n. 碎片 v. 废弃"},{"scrutiny","n. 详细审查；细看"},
        {"seemingly","adv. 表面上；似乎"},{"sentiment","n. 感情；情绪"},
        {"shatter","v. 粉碎；破灭"},{"shrewd","adj. 精明的；狡猾的"},
        {"shrug","n./v. 耸肩"},{"shuttle","n. 穿梭；航天飞机"},
        {"siege","n. 包围；围攻"},{"signify","v. 表示；意味着"},
        {"simulate","v. 模拟；假装"},{"simultaneous","adj. 同时发生的"},
        {"skeptical","adj. 怀疑的；怀疑论的"},{"slack","adj. 松弛的 n. 松弛部分"},
        {"slash","v. 大幅度削减；砍"},{"slaughter","n./v. 屠杀；屠宰"},
        {"slim","adj. 苗条的；微小的"},{"slogan","n. 口号；标语"},
        {"slump","v. 暴跌 n. 暴跌"},{"smuggle","v. 走私；偷运"},
        {"snatch","v. 抢夺；抓住"},{"sober","adj. 清醒的；严肃的"},
        {"solicitor","n. 律师；推销员"},{"solidarity","n. 团结一致"},
        {"solitary","adj. 孤独的；单个的"},{"sovereign","n. 君主 adj. 至高无上的"},
        {"sparkle","v. 闪耀 n. 闪光"},{"specialty","n. 专业；专长"},
        {"specification","n. 规格；规范"},{"spectacle","n. 景象；奇观"},
        {"spectator","n. 观众；旁观者"},{"spectrum","n. 光谱；范围"},
        {"speculate","v. 推测；投机"},{"spiral","adj. 螺旋的 n. 螺旋"},
        {"splash","v. 溅；泼 n. 飞溅声"},{"spontaneous","adj. 自发的；自然的"},
        {"spouse","n. 配偶"},{"stabilize","v. 使稳定"},{"stagger","v. 蹒跚；使震惊"},
        {"stalk","v. 跟踪 n. 茎秆"},{"stall","n. 摊位 v. 拖延"},
        {"startle","v. 使吃惊；惊吓"},{"stationary","adj. 静止的；不变的"},
        {"stereotype","n. 刻板印象 v. 使模式化"},{"stimulus","n. 刺激；激励"},
        {"stitch","n. 一针 v. 缝"},{"straightforward","adj. 直截了当的"},
        {"strand","n. 线；缕 v. 使搁浅"},{"strategic","adj. 战略的；关键的"},
        {"streamline","v. 精简；使流线型"},{"stride","n. 大步 v. 大步走"},
        {"strive","v. 努力；奋斗"},{"stubborn","adj. 顽固的；倔强的"},
        {"stun","v. 使震惊；使昏迷"},{"subjective","adj. 主观的"},
        {"submarine","n. 潜水艇 adj. 海底的"},{"subordinate","adj. 下级的 n. 下属"},
        {"subscribe","v. 订阅；同意"},{"subsidiary","adj. 辅助的 n. 子公司"},
        {"subsidy","n. 补贴；津贴"},{"subtle","adj. 微妙的；精细的"},
        {"successor","n. 继任者；接班人"},{"sue","v. 起诉；控告"},
        {"suffice","v. 足够；充足"},{"suite","n. 套房；一套"},
        {"summit","n. 峰会；顶峰"},{"summon","v. 召唤；召集"},
        {"superb","adj. 极好的；卓越的"},{"superficial","adj. 表面的；肤浅的"},
        {"supersonic","adj. 超音速的"},{"suppress","v. 压制；抑制"},
        {"surge","n. 激增 v. 汹涌"},{"surpass","v. 超越；胜过"},
        {"susceptible","adj. 易受影响的；敏感的"},{"suspension","n. 暂停；悬挂"},
        {"suspicious","adj. 可疑的；怀疑的"},{"swamp","n. 沼泽 v. 淹没"},
        {"symmetry","n. 对称；匀称"},{"symphony","n. 交响乐"},
        {"symposium","n. 研讨会；讨论会"},{"symptom","n. 症状；征兆"},
        {"synthesis","n. 合成；综合"},{"tablet","n. 药片；平板"},
        {"tackle","v. 处理 n. 装备"},{"tangle","v. 纠缠 n. 混乱"},
        {"tariff","n. 关税；税率"},{"tease","v. 戏弄；取笑"},
        {"tedious","adj. 乏味的；冗长的"},{"temperament","n. 气质；性格"},
        {"tempt","v. 诱惑；引诱"},{"tenant","n. 租户；房客"},
        {"tentative","adj. 试探性的；暂定的"},{"terminate","v. 结束；终止"},
        {"terrace","n. 梯田；露台"},{"terrain","n. 地形；地势"},
        {"terrific","adj. 极好的；可怕的"},{"testify","v. 作证；证明"},
        {"testimony","n. 证词；证据"},{"texture","n. 质地；纹理"},
        {"threshold","n. 门槛；界限"},{"thrill","n. 激动 v. 使兴奋"},
        {"thrive","v. 繁荣；兴旺"},{"token","n. 象征；代币"},
        {"toss","v. 抛；扔"},{"tow","v. 拖；牵引 n. 拖曳"},
        {"toxic","adj. 有毒的"},{"trait","n. 特征；特性"},
        {"transaction","n. 交易；业务"},{"transcend","v. 超越；胜过"},
        {"transient","adj. 短暂的；临时的"},{"transit","n. 运输；过境"},
        {"transition","n. 过渡；转变"},{"transplant","v. 移植 n. 移植"},
        {"traverse","v. 横穿；穿过"},{"trench","n. 沟渠；战壕"},
        {"tribe","n. 部落；种族"},{"tribute","n. 贡品；致敬"},
        {"trifle","n. 琐事 v. 怠慢"},{"triple","adj. 三倍的 v. 成为三倍"},
        {"trivial","adj. 琐碎的；不重要的"},{"tuck","v. 塞进；卷起"},
        {"tug","v. 用力拉 n. 拖船"},{"tuition","n. 学费；教学"},
        {"tumble","v. 跌倒；暴跌"},{"turbulent","adj. 动荡的；湍急的"},
        {"turnover","n. 营业额；人员流动"},{"ultraviolet","adj. 紫外线的"},
        {"unanimous","adj. 一致的；全票通过的"},{"underestimate","v. 低估 n. 低估"},
        {"underlying","adj. 潜在的；根本的"},{"undermine","v. 破坏；削弱"},
        {"unify","v. 统一；联合"},{"update","v. 更新 n. 最新信息"},
        {"upgrade","v. 升级 n. 升级"},{"uphold","v. 支持；维护"},
        {"utilize","v. 利用；使用"},{"utmost","adj. 极度的 n. 最大可能"},
        {"vacant","adj. 空着的；空缺的"},{"vaccine","n. 疫苗"},
        {"vague","adj. 模糊的；含糊的"},{"validity","n. 有效性；合法性"},
        {"veil","n. 面纱 v. 遮掩"},{"ventilate","v. 通风；公开讨论"},
        {"verbal","adj. 口头的；言语的"},{"verdict","n. 裁决；结论"},
        {"verge","n. 边缘 v. 接近"},{"versatile","adj. 多才多艺的；多功能的"},
        {"verse","n. 诗；韵文"},{"veto","n./v. 否决"},{"vicinity","n. 附近；邻近"},
        {"vicious","adj. 恶毒的；凶猛的"},{"violate","v. 违反；侵犯"},
        {"vocal","adj. 发声的；直言不讳的"},{"vocational","adj. 职业的"},
        {"void","adj. 空的 n. 空白；空虚"},{"vulgar","adj. 粗俗的；庸俗的"},
        {"vulnerable","adj. 脆弱的；易受伤的"},{"ward","n. 病房 v. 避开"},
        {"warfare","n. 战争；冲突"},{"warrant","n. 授权令 v. 保证"},
        {"watertight","adj. 不漏水的；无懈可击的"},{"weary","adj. 疲倦的 v. 使疲倦"},
        {"weird","adj. 奇怪的；怪异的"},{"whirl","v. 旋转 n. 旋转"},
        {"withhold","v. 扣留；保留"},{"wreck","n. 残骸 v. 破坏"},
        {"wrench","v. 猛扭 n. 扳手"},{"wrinkle","n. 皱纹 v. 起皱"},
    };

    // ══════════════════ IELTS 词库 (~400词) ══════════════════
    static final String[][] IELTS = {
        {"abandon","v. 放弃；遗弃"},{"absorb","v. 吸收；吸引"},
        {"abuse","n./v. 滥用；虐待"},{"academy","n. 学院；研究院"},
        {"accelerate","v. 加速；促进"},{"accommodation","n. 住宿；膳宿"},
        {"accompany","v. 陪伴；伴随"},{"accomplish","v. 完成；实现"},
        {"accumulate","v. 积累；积聚"},{"accurate","adj. 准确的；精确的"},
        {"achieve","v. 达到；取得"},{"acknowledge","v. 承认；确认"},
        {"acquire","v. 获得；学到"},{"adapt","v. 适应；改编"},
        {"adequate","adj. 足够的；适当的"},{"adjust","v. 调整；适应"},
        {"administration","n. 管理；行政"},{"adolescent","n. 青少年 adj. 青春期的"},
        {"advantageous","adj. 有利的；有益的"},{"advertise","v. 做广告；宣传"},
        {"affordable","adj. 负担得起的；价格合理的"},{"aggressive","adj. 侵略的；好斗的"},
        {"agriculture","n. 农业；农学"},{"allocate","v. 分配；拨出"},
        {"alternative","n. 替代方案 adj. 替代的"},{"ambiguous","adj. 含糊的；模棱两可的"},
        {"ambitious","adj. 有雄心的；野心勃勃的"},{"analysis","n. 分析；解析"},
        {"announcement","n. 公告；通告"},{"anonymous","adj. 匿名的；无名的"},
        {"antibiotic","n. 抗生素 adj. 抗生的"},{"anticipate","v. 预期；期望"},
        {"anxiety","n. 焦虑；忧虑"},{"apparatus","n. 器械；装置"},
        {"apparently","adv. 显然；表面上"},{"appreciation","n. 欣赏；感激"},
        {"approach","v. 接近 n. 方法"},{"appropriate","adj. 适当的 v. 占用"},
        {"approximately","adv. 大约；近似地"},{"arbitrary","adj. 任意的；武断的"},
        {"architecture","n. 建筑学；结构"},{"arrangement","n. 安排；整理"},
        {"assessment","n. 评估；评定"},{"assignment","n. 任务；作业"},
        {"assistance","n. 帮助；援助"},{"association","n. 协会；联系"},
        {"assumption","n. 假定；设想"},{"atmosphere","n. 气氛；大气层"},
        {"attainment","n. 达到；成就"},{"attendance","n. 出席；到场"},
        {"attractive","adj. 有吸引力的"},{"authoritative","adj. 权威的；官方的"},
        {"automatically","adv. 自动地"},{"availability","n. 可用性；有效性"},
        {"awareness","n. 意识；认识"},{"bankruptcy","n. 破产；倒闭"},
        {"basically","adv. 基本上；主要地"},{"behaviour","n. 行为；举止"},
        {"beneficial","adj. 有益的；有利的"},{"bibliography","n. 参考书目"},
        {"biodiversity","n. 生物多样性"},{"biological","adj. 生物的；生物学的"},
        {"breakthrough","n. 突破；重大进展"},{"broadcast","n./v. 广播；播送"},
        {"bureaucracy","n. 官僚机构"},{"calculation","n. 计算；估计"},
        {"capability","n. 能力；才能"},{"catastrophic","adj. 灾难性的"},
        {"celebration","n. 庆祝；庆典"},{"challenging","adj. 有挑战性的"},
        {"characteristic","n. 特征 adj. 特有的"},{"chronological","adj. 按时间顺序的"},
        {"circulation","n. 循环；发行量"},{"circumstance","n. 环境；情况"},
        {"civilization","n. 文明；文化"},{"classification","n. 分类；分级"},
        {"collaboration","n. 合作；协作"},{"colonial","adj. 殖民的；殖民地的"},
        {"commentary","n. 评论；解说"},{"commitment","n. 承诺；投入"},
        {"commodity","n. 商品；货物"},{"compensation","n. 补偿；赔偿"},
        {"competition","n. 竞争；比赛"},{"complementary","adj. 补充的；互补的"},
        {"complication","n. 复杂；并发症"},{"comprehensive","adj. 全面的；综合的"},
        {"concentration","n. 集中；专注"},{"confederation","n. 联盟；联邦"},
        {"configuration","n. 配置；结构"},{"confrontation","n. 对抗；对峙"},
        {"congratulation","n. 祝贺；贺词"},{"consciousness","n. 意识；知觉"},
        {"constitutional","adj. 宪法的；体制的"},{"construction","n. 建设；建筑"},
        {"consultation","n. 咨询；商议"},{"consumption","n. 消费；消耗"},
        {"contamination","n. 污染；玷污"},{"contemporary","adj. 当代的；同时代的"},
        {"contradiction","n. 矛盾；反驳"},{"contribution","n. 贡献；捐献"},
        {"controversial","adj. 有争议的"},{"conventional","adj. 传统的；常规的"},
        {"cooperation","n. 合作；协作"},{"coordination","n. 协调；配合"},
        {"correspondence","n. 通信；对应"},{"creativity","n. 创造力；创造性"},
        {"curriculum","n. 课程；全部课程"},{"deforestation","n. 森林砍伐；滥伐"},
        {"demonstration","n. 示范；示威"},{"depreciation","n. 贬值；折旧"},
        {"determination","n. 决心；决定"},{"deterioration","n. 恶化；退化"},
        {"development","n. 发展；开发"},{"discrimination","n. 歧视；辨别"},
        {"dissertation","n. 论文；专题论文"},{"distribution","n. 分配；分布"},
        {"diversification","n. 多样化；多元"},{"documentation","n. 文件；文献"},
        {"earthquake","n. 地震"},{"economical","adj. 经济的；节约的"},
        {"educational","adj. 教育的；有教育意义的"},{"effectiveness","n. 有效性；效力"},
        {"efficiency","n. 效率；效能"},{"electricity","n. 电力；电流"},
        {"eligibility","n. 资格；合格"},{"employment","n. 就业；雇佣"},
        {"encyclopedia","n. 百科全书"},{"enforcement","n. 执行；强制"},
        {"entertainment","n. 娱乐；款待"},{"entrepreneur","n. 企业家"},
        {"environment","n. 环境"},{"equipment","n. 设备；装备"},
        {"establishment","n. 建立；机构"},{"evaluation","n. 评估；评价"},
        {"exaggeration","n. 夸张；夸大"},{"examination","n. 考试；检查"},
        {"expenditure","n. 支出；花费"},{"exploitation","n. 开发；剥削"},
        {"exploration","n. 探索；勘探"},{"facilitation","n. 促进；便利化"},
        {"fascinating","adj. 迷人的；极有吸引力的"},{"fluctuation","n. 波动；起伏"},
        {"foundation","n. 基础；基金会"},{"fragmentation","n. 分裂；碎片化"},
        {"frustration","n. 挫折；沮丧"},{"fundamental","adj. 基本的 n. 基础"},
        {"generalization","n. 概括；普遍化"},{"globalization","n. 全球化"},
        {"government","n. 政府；治理"},{"habitation","n. 居住；栖息地"},
        {"harmonious","adj. 和谐的；和睦的"},{"hospitality","n. 好客；款待"},
        {"identification","n. 识别；身份证明"},{"illustration","n. 说明；插图"},
        {"imagination","n. 想象力；创造"},{"immigration","n. 移民；移居"},
        {"implementation","n. 实施；执行"},{"implication","n. 含义；暗示"},
        {"independence","n. 独立；自主"},{"industrialization","n. 工业化"},
        {"inequality","n. 不平等；不平均"},{"infrastructure","n. 基础设施"},
        {"innovation","n. 创新；革新"},{"institution","n. 机构；制度"},
        {"integration","n. 整合；融合"},{"intelligence","n. 智力；情报"},
        {"interaction","n. 互动；相互作用"},{"interpretation","n. 解释；口译"},
        {"intervention","n. 干预；介入"},{"introduction","n. 介绍；引进"},
        {"investigation","n. 调查；研究"},{"investment","n. 投资；投入"},
        {"involvement","n. 参与；卷入"},{"irrigation","n. 灌溉"},
        {"journalism","n. 新闻业；新闻学"},{"justification","n. 正当理由；辩护"},
        {"knowledge","n. 知识；学问"},{"legislation","n. 立法；法规"},
        {"likelihood","n. 可能性；概率"},{"limitation","n. 限制；局限性"},
        {"maintenance","n. 维持；保养"},{"management","n. 管理；经营"},
        {"manufacturing","n. 制造业 adj. 制造的"},{"measurement","n. 测量；大小"},
        {"mechanism","n. 机制；机械装置"},{"medication","n. 药物；药物治疗"},
        {"methodology","n. 方法论；方法"},{"migration","n. 迁移；移民"},
        {"mobilization","n. 动员；调动"},{"modification","n. 修改；调整"},
        {"monitoring","n. 监测；监控"},{"motivation","n. 动机；积极性"},
        {"negotiation","n. 谈判；协商"},{"notification","n. 通知；通告"},
        {"nutrition","n. 营养；营养学"},{"observation","n. 观察；评论"},
        {"occupation","n. 职业；占领"},{"opportunity","n. 机会；时机"},
        {"organization","n. 组织；机构"},{"orientation","n. 方向；定位"},
        {"ownership","n. 所有权；物主身份"},{"participation","n. 参与；参加"},
        {"perception","n. 感知；理解"},{"performance","n. 表现；性能"},
        {"permission","n. 允许；许可"},{"personality","n. 个性；人格"},
        {"phenomenon","n. 现象；奇迹"},{"philosophy","n. 哲学；人生观"},
        {"photography","n. 摄影；摄影术"},{"pollution","n. 污染；玷污"},
        {"population","n. 人口；全体居民"},{"possession","n. 拥有；财产"},
        {"possibility","n. 可能性；可能"},{"poverty","n. 贫穷；贫困"},
        {"preparation","n. 准备；预备"},{"preservation","n. 保存；保护"},
        {"prevention","n. 预防；阻止"},{"probability","n. 可能性；概率"},
        {"production","n. 生产；产量"},{"productivity","n. 生产力；生产率"},
        {"professionalism","n. 专业精神；职业水准"},{"programming","n. 编程；程序设计"},
        {"prohibition","n. 禁止；禁令"},{"proliferation","n. 扩散；激增"},
        {"promotion","n. 促进；晋升"},{"pronunciation","n. 发音；读法"},
        {"proportion","n. 比例；部分"},{"prosecution","n. 起诉；控告"},
        {"protection","n. 保护；防护"},{"psychology","n. 心理学；心理"},
        {"publication","n. 出版；出版物"},{"qualification","n. 资格；条件"},
        {"recognition","n. 认出；承认"},{"recommendation","n. 推荐；建议"},
        {"recycling","n. 回收利用"},{"reduction","n. 减少；缩减"},
        {"reflection","n. 反映；反思"},{"registration","n. 登记；注册"},
        {"regulation","n. 规则；管理"},{"rehabilitation","n. 康复；修复"},
        {"reinforcement","n. 加强；加固"},{"relationship","n. 关系；关联"},
        {"reliability","n. 可靠性；可信度"},{"relocation","n. 搬迁；重新安置"},
        {"reproduction","n. 繁殖；复制"},{"reputation","n. 名声；声誉"},
        {"requirement","n. 要求；必要条件"},{"reservation","n. 预订；保留"},
        {"resignation","n. 辞职；顺从"},{"resolution","n. 决心；决议"},
        {"responsibility","n. 责任；职责"},{"restoration","n. 恢复；修复"},
        {"restriction","n. 限制；约束"},{"retirement","n. 退休；退役"},
        {"revelation","n. 揭示；启示"},{"revolution","n. 革命；变革"},
        {"satisfaction","n. 满足；满意"},{"scholarship","n. 奖学金；学问"},
        {"separation","n. 分离；分开"},{"significance","n. 重要性；意义"},
        {"similarity","n. 相似；类似"},{"specialization","n. 专业化；专长"},
        {"specification","n. 规格；规范"},{"standardization","n. 标准化"},
        {"statistics","n. 统计学；统计数字"},{"stimulation","n. 刺激；激励"},
        {"submission","n. 提交；服从"},{"supervision","n. 监督；管理"},
        {"sustainability","n. 可持续性"},{"systematic","adj. 系统的；有组织的"},
        {"technician","n. 技术员；技师"},{"temperature","n. 温度；体温"},
        {"termination","n. 终止；结束"},{"transformation","n. 转变；变形"},
        {"transportation","n. 运输；交通"},{"uncertainty","n. 不确定性；不确定"},
        {"undergraduate","n. 本科生 adj. 本科的"},{"understanding","n. 理解；谅解 adj. 通情达理的"},
        {"unemployment","n. 失业；失业率"},{"urbanization","n. 城市化"},
        {"utilization","n. 利用；使用"},{"vaccination","n. 疫苗接种"},
        {"variability","n. 可变性；变化性"},{"ventilation","n. 通风；通风设备"},
        {"verification","n. 验证；核实"},{"violation","n. 违反；侵犯"},
        {"visualization","n. 可视化；形象化"},{"volunteer","n. 志愿者 adj. 志愿的"},
        {"vulnerability","n. 脆弱性；易受伤"},{"wilderness","n. 荒野；荒原"},
        {"withdrawal","n. 撤回；提款"},{"workmanship","n. 手艺；工艺"},
    };

    // ══════════════════ TOEFL 词库 (~400词) ══════════════════
    static final String[][] TOEFL = {
        {"abandon","v. 放弃；遗弃"},{"abbreviation","n. 缩写；缩写词"},
        {"abolish","v. 废除；取消"},{"abrupt","adj. 突然的；唐突的"},
        {"abstract","adj. 抽象的 n. 摘要"},{"absurd","adj. 荒谬的；可笑的"},
        {"abundance","n. 丰富；充裕"},{"abuse","n./v. 滥用；虐待"},
        {"academy","n. 学院；研究院"},{"accelerate","v. 加速；促进"},
        {"accessible","adj. 可接近的；易理解的"},{"accommodate","v. 容纳；适应"},
        {"accompany","v. 陪伴；伴随"},{"accomplish","v. 完成；实现"},
        {"accumulate","v. 积累；积聚"},{"accurate","adj. 准确的；精确的"},
        {"achieve","v. 达到；取得"},{"acknowledge","v. 承认；确认"},
        {"acquire","v. 获得；学到"},{"adapt","v. 适应；改编"},
        {"adequate","adj. 足够的；适当的"},{"adhere","v. 粘附；坚持"},
        {"adjacent","adj. 邻近的；毗连的"},{"adjust","v. 调整；适应"},
        {"administer","v. 管理；执行"},{"adolescent","n. 青少年 adj. 青春期的"},
        {"advance","n./v. 前进；进步"},{"adverse","adj. 不利的；相反的"},
        {"advocate","v. 提倡；主张 n. 倡导者"},{"aesthetic","adj. 美学的；审美的"},
        {"affect","v. 影响；感动"},{"aggregate","v. 聚集 n. 总计"},
        {"agitate","v. 搅动；煽动"},{"albeit","conj. 虽然；即使"},
        {"allocate","v. 分配；拨出"},{"alter","v. 改变；修改"},
        {"alternative","n. 替代方案 adj. 替代的"},{"ambiguous","adj. 含糊的；模棱两可的"},
        {"ambitious","adj. 有雄心的"},{"ameliorate","v. 改善；改良"},
        {"amend","v. 修改；修订"},{"ample","adj. 充足的；丰富的"},
        {"analogy","n. 类比；相似"},{"analyze","v. 分析；解析"},
        {"ancestor","n. 祖先；祖宗"},{"anecdote","n. 轶事；趣闻"},
        {"annihilate","v. 消灭；歼灭"},{"annual","adj. 每年的 n. 年刊"},
        {"antagonism","n. 对抗；敌对"},{"anticipate","v. 预期；期望"},
        {"apparent","adj. 明显的；表面上的"},{"appeal","n./v. 呼吁；吸引"},
        {"append","v. 附加；添加"},{"appreciate","v. 欣赏；感激"},
        {"approach","v. 接近 n. 方法"},{"appropriate","adj. 适当的 v. 占用"},
        {"approximately","adv. 大约；近似地"},{"arbitrary","adj. 任意的；武断的"},
        {"articulate","v. 清晰表达 adj. 口齿伶俐的"},{"ascribe","v. 把…归因于"},
        {"aspect","n. 方面；外貌"},{"assemble","v. 集合；组装"},
        {"assert","v. 断言；坚持"},{"assess","v. 评估；评定"},
        {"assign","v. 分配；指派"},{"assist","v. 帮助；协助"},
        {"assume","v. 假定；承担"},{"attain","v. 达到；获得"},
        {"attitude","n. 态度；看法"},{"attribute","v. 归因于 n. 属性"},
        {"augment","v. 增加；扩大"},{"authentic","adj. 真实的；可靠的"},
        {"authority","n. 权威；当局"},{"autonomous","adj. 自治的；自主的"},
        {"avail","v. 有益于 n. 效用"},{"avert","v. 避免；转移"},
        {"barrier","n. 障碍；屏障"},{"behalf","n. 代表；利益"},
        {"belittle","v. 贬低；轻视"},{"beneficial","adj. 有益的；有利的"},
        {"bias","n. 偏见 v. 使有偏见"},{"bizarre","adj. 奇异的；古怪的"},
        {"bolster","v. 支持；加强"},{"boom","n. 繁荣 v. 激增"},
        {"boon","n. 恩惠；福利"},{"brevity","n. 简洁；短暂"},
        {"bulk","n. 大量；大部分"},{"burgeon","v. 迅速发展；萌芽"},
        {"capable","adj. 有能力的"},{"capacity","n. 能力；容量"},
        {"catalyst","n. 催化剂；促进因素"},{"catastrophe","n. 大灾难；灾祸"},
        {"cease","v. 停止；终止"},{"channel","n. 频道；渠道"},
        {"chronic","adj. 慢性的；长期的"},{"circumvent","v. 规避；绕过"},
        {"cite","v. 引用；引证"},{"clarify","v. 澄清；阐明"},
        {"coerce","v. 强迫；强制"},{"coherent","adj. 连贯的；一致的"},
        {"coincide","v. 同时发生；一致"},{"collapse","v./n. 倒塌；崩溃"},
        {"commence","v. 开始；着手"},{"commission","n. 委员会；佣金 v. 委托"},
        {"commit","v. 犯（罪）；承诺"},{"commodity","n. 商品；货物"},
        {"compatible","adj. 兼容的；合得来的"},{"compensate","v. 补偿；赔偿"},
        {"compile","v. 编译；汇编"},{"complement","v. 补充 n. 补足物"},
        {"comply","v. 遵守；顺从"},{"component","n. 组成部分；部件"},
        {"comprehensive","adj. 全面的；综合的"},{"comprise","v. 包含；由…组成"},
        {"compulsory","adj. 强制的；必修的"},{"conceive","v. 构想；怀孕"},
        {"concentrate","v. 集中；浓缩"},{"concise","adj. 简洁的；简明的"},
        {"conclusive","adj. 决定性的；结论性的"},{"concurrent","adj. 同时发生的"},
        {"condone","v. 宽恕；容忍"},{"confine","v. 限制；禁闭"},
        {"confirm","v. 确认；证实"},{"conform","v. 遵守；符合"},
        {"confront","v. 面对；对抗"},{"congregate","v. 聚集；集合"},
        {"conjecture","n./v. 推测；猜测"},{"conscientious","adj. 认真负责的"},
        {"consensus","n. 共识；一致意见"},{"consequent","adj. 随之发生的"},
        {"conserve","v. 保存；节约"},{"considerable","adj. 相当大的；重要的"},
        {"consist","v. 由…组成；在于"},{"consistent","adj. 一致的；始终如一的"},
        {"consolidate","v. 巩固；合并"},{"conspicuous","adj. 显眼的；明显的"},
        {"constant","adj. 不变的；持续的"},{"constitute","v. 构成；组成"},
        {"constrain","v. 限制；约束"},{"construct","v. 建造；构建"},
        {"consult","v. 咨询；查阅"},{"consume","v. 消费；消耗"},
        {"contaminate","v. 污染；玷污"},{"contemporary","adj. 当代的；同时代的"},
        {"contend","v. 竞争；主张"},{"context","n. 背景；上下文"},
        {"contradict","v. 矛盾；反驳"},{"contribute","v. 贡献；捐献"},
        {"controversy","n. 争议；争论"},{"convene","v. 召集；集合"},
        {"conventional","adj. 传统的；常规的"},{"converge","v. 聚集；汇合"},
        {"converse","v. 交谈 adj. 相反的"},{"convert","v. 转换；转变"},
        {"convey","v. 传达；运送"},{"convince","v. 说服；使确信"},
        {"cooperate","v. 合作；协作"},{"coordinate","v. 协调 n. 坐标"},
        {"cope","v. 应对；处理"},{"correlate","v. 使相关联"},
        {"correspond","v. 通信；对应"},{"corroborate","v. 证实；确证"},
        {"counterpart","n. 对应物；职位相同的人"},{"crucial","adj. 至关重要的"},
        {"cumulative","adj. 累积的；渐增的"},{"curtail","v. 削减；缩短"},
        {"cynical","adj. 愤世嫉俗的；怀疑的"},{"debilitate","v. 使虚弱；削弱"},
        {"decipher","v. 破译；解读"},{"decline","n./v. 下降；衰退"},
        {"decompose","v. 分解；腐烂"},{"dedicate","v. 奉献；致力于"},
        {"deem","v. 认为；视为"},{"deficiency","n. 缺乏；不足"},
        {"definitive","adj. 确定的；决定性的"},{"deflect","v. 使偏转；转移"},
        {"deforestation","n. 森林砍伐；滥伐"},{"degradation","n. 退化；降级"},
        {"delegate","v. 委托；选派 n. 代表"},{"deliberate","adj. 故意的 v. 仔细考虑"},
        {"delicate","adj. 精致的；微妙的"},{"demographic","adj. 人口统计的"},
        {"demonstrate","v. 证明；示范"},{"denote","v. 表示；意味着"},
        {"depict","v. 描绘；描述"},{"deplete","v. 耗尽；大量减少"},
        {"deploy","v. 部署；利用"},{"depreciate","v. 贬值；贬低"},
        {"depress","v. 使沮丧；压低"},{"derive","v. 源自；获得"},
        {"designate","v. 指定；任命"},{"deter","v. 阻止；威慑"},
        {"deteriorate","v. 恶化；退化"},{"detrimental","adj. 有害的；不利的"},
        {"devastate","v. 毁灭；摧毁"},{"deviate","v. 偏离；背离"},
        {"devise","v. 设计；发明"},{"differentiate","v. 区分；辨别"},
        {"diffuse","v. 扩散；传播 adj. 弥漫的"},{"dilemma","n. 困境；进退两难"},
        {"diminish","v. 减少；缩小"},{"discern","v. 辨别；识别"},
        {"discourse","n. 论述；话语"},{"discrepancy","n. 差异；不一致"},
        {"discrete","adj. 离散的；分离的"},{"discriminate","v. 歧视；区别"},
        {"disdain","n./v. 蔑视；鄙视"},{"disperse","v. 分散；驱散"},
        {"displace","v. 取代；置换"},{"dispose","v. 处理；安排"},
        {"dispute","n./v. 争论；争执"},{"disrupt","v. 扰乱；中断"},
        {"disseminate","v. 传播；散布"},{"dissolve","v. 溶解；解散"},
        {"distinct","adj. 截然不同的；清楚的"},{"distort","v. 扭曲；歪曲"},
        {"distribute","v. 分配；分发"},{"diverse","adj. 多样的；不同的"},
        {"document","v. 记录 n. 文件"},{"domain","n. 领域；范围"},
        {"domestic","adj. 国内的；家庭的"},{"dominate","v. 支配；主导"},
        {"dormant","adj. 休眠的；静止的"},{"draft","n. 草稿 v. 起草"},
        {"drastic","adj. 激烈的；极端的"},{"drawback","n. 缺点；不利条件"},
        {"drought","n. 干旱"},{"duration","n. 持续时间；期间"},
        {"dynamic","adj. 动态的；有活力的"},{"eclipse","n. 日食 v. 使黯然失色"},
        {"ecology","n. 生态学"},{"elaborate","adj. 精心制作的 v. 详细阐述"},
        {"elevate","v. 提升；提高"},{"elicit","v. 引出；探出"},
        {"eliminate","v. 消除；淘汰"},{"eloquent","adj. 有口才的；雄辩的"},
        {"elusive","adj. 难以捉摸的；逃避的"},{"emanate","v. 发出；散发"},
        {"embark","v. 着手；上船"},{"embed","v. 嵌入；植入"},
        {"embrace","v. 拥抱；包含"},{"emerge","v. 出现；浮现"},
        {"eminent","adj. 杰出的；著名的"},{"emit","v. 发出；散发"},
        {"empathy","n. 共情；同情"},{"empirical","adj. 经验主义的"},
        {"empower","v. 授权；赋予权力"},{"enable","v. 使能够；启用"},
        {"encompass","v. 包含；包围"},{"encounter","n./v. 遭遇；邂逅"},
        {"endeavor","n./v. 努力；尽力"},{"endorse","v. 支持；背书"},
        {"endure","v. 忍受；持续"},{"enforce","v. 执行；强制"},
        {"engage","v. 从事；订婚"},{"enhance","v. 增强；提高"},
        {"enormous","adj. 巨大的；庞大的"},{"enrich","v. 丰富；使充实"},
        {"ensue","v. 继而发生；随之而来"},{"ensure","v. 确保；保证"},
        {"entail","v. 需要；牵涉"},{"entity","n. 实体；存在物"},
        {"entrepreneur","n. 企业家"},{"envision","v. 想象；设想"},
        {"episode","n. 插曲；一段经历"},{"equitable","adj. 公平的；公正的"},
        {"equivalent","adj. 等价的 n. 等价物"},{"eradicate","v. 根除；消灭"},
        {"erode","v. 侵蚀；腐蚀"},{"erupt","v. 爆发；喷发"},
        {"escalate","v. 升级；加剧"},{"essence","n. 本质；精华"},
        {"establish","v. 建立；确立"},{"estimate","n./v. 估计；估算"},
        {"evade","v. 逃避；回避"},{"evaluate","v. 评估；评价"},
        {"eventually","adv. 最终；终于"},{"evidence","n. 证据；迹象"},
        {"evolve","v. 进化；发展"},{"exacerbate","v. 加重；恶化"},
        {"exceed","v. 超过；超越"},{"exclude","v. 排除；排斥"},
        {"exclusive","adj. 独家的；排外的"},{"execute","v. 执行；处决"},
        {"exemplify","v. 举例说明"},{"exert","v. 施加；运用"},
        {"exhaust","v. 耗尽；使筋疲力尽"},{"exhibit","n./v. 展览；展示"},
        {"expand","v. 扩张；扩展"},{"expedite","v. 加速；促进"},
        {"expenditure","n. 支出；花费"},{"expertise","n. 专长；专门知识"},
        {"exploit","v. 开发；剥削"},{"exponential","adj. 指数的；指数增长的"},
        {"expose","v. 暴露；揭露"},{"expound","v. 阐述；解释"},
        {"extensive","adj. 广泛的；大量的"},{"external","adj. 外部的；外面的"},
        {"extinguish","v. 熄灭；消灭"},{"extract","v. 提取 n. 摘录"},
        {"extrapolate","v. 推断；外推"},{"fabricate","v. 制造；捏造"},
        {"facilitate","v. 促进；使便利"},{"factor","n. 因素；因子"},
        {"feasible","adj. 可行的；可能的"},{"fluctuate","v. 波动；涨落"},
        {"formulate","v. 制定；规划"},{"foster","v. 培养；促进"},
        {"foundation","n. 基础；基金会"},{"framework","n. 框架；结构"},
        {"friction","n. 摩擦；冲突"},{"fundamental","adj. 基本的 n. 基础"},
        {"furthermore","adv. 此外；而且"},{"generate","v. 产生；生成"},
        {"gradual","adj. 逐渐的；逐步的"},{"grant","v. 授予 n. 拨款"},
        {"guarantee","n./v. 保证；担保"},{"hamper","v. 妨碍；阻碍"},
        {"hence","adv. 因此；所以"},{"hierarchy","n. 等级制度；层级"},
        {"highlight","v. 强调 n. 亮点"},{"hinder","v. 阻碍；妨碍"},
        {"hypothesis","n. 假设；假说"},{"identical","adj. 相同的；同一的"},
        {"identify","v. 识别；鉴定"},{"ideology","n. 意识形态"},
        {"ignorance","n. 无知；愚昧"},{"illuminate","v. 照亮；阐明"},
        {"illustrate","v. 说明；举例"},{"immense","adj. 巨大的；广大的"},
        {"immerse","v. 沉浸；使陷入"},{"impact","n./v. 影响；冲击"},
        {"impair","v. 损害；削弱"},{"impede","v. 阻碍；妨碍"},
        {"implement","v. 实施 n. 工具"},{"implication","n. 含义；暗示"},
        {"implicit","adj. 含蓄的；内含的"},{"impose","v. 强加；征税"},
        {"impoverish","v. 使贫困；使贫瘠"},{"incentive","n. 激励；刺激"},
        {"incidence","n. 发生率；影响范围"},{"incorporate","v. 包含；合并"},
        {"indigenous","adj. 本土的；土著的"},{"indispensable","adj. 不可或缺的"},
        {"induce","v. 引起；诱导"},{"inevitable","adj. 不可避免的"},
        {"inferior","adj. 低劣的；下级的"},{"infrastructure","n. 基础设施"},
        {"inhabit","v. 居住于；栖息于"},{"inherent","adj. 固有的；内在的"},
        {"inhibit","v. 抑制；禁止"},{"initiate","v. 开始；发起"},
        {"innovate","v. 创新；革新"},{"insight","n. 洞察力；深刻见解"},
        {"integral","adj. 必需的；完整的"},{"integrate","v. 整合；融合"},
        {"interact","v. 互动；相互作用"},{"interfere","v. 干涉；干扰"},
        {"interpret","v. 解释；口译"},{"intervene","v. 干涉；介入"},
        {"intrinsic","adj. 固有的；内在的"},{"investigate","v. 调查；研究"},
        {"invoke","v. 调用；援引"},{"involve","v. 涉及；包含"},
        {"isolate","v. 隔离；孤立"},{"justify","v. 证明…有理"},
        {"launch","n./v. 发射；启动"},{"legislate","v. 立法；制定法律"},
        {"levy","v. 征收 n. 税款"},{"liberal","adj. 自由的；开明的"},
        {"likewise","adv. 同样地；也"},{"magnitude","n. 大小；重要性"},
        {"maintain","v. 维持；保养"},{"manifest","v. 表明 adj. 明显的"},
        {"manipulate","v. 操纵；操作"},{"margin","n. 边缘；利润"},
        {"maximize","v. 最大化"},{"mechanism","n. 机制；机械装置"},
        {"mediate","v. 调解；斡旋"},{"merge","v. 合并；融合"},
        {"methodology","n. 方法论；方法"},{"migrate","v. 迁移；移居"},
        {"minimize","v. 最小化；降到最低"},{"modify","v. 修改；调整"},
        {"monitor","n./v. 监控；监视"},{"moreover","adv. 此外；而且"},
        {"motivate","v. 激励；激发"},{"navigate","v. 导航；航行"},
        {"negate","v. 否定；取消"},{"negotiate","v. 谈判；协商"},
        {"nevertheless","adv. 尽管如此"},{"nonetheless","adv. 尽管如此"},
        {"notion","n. 概念；想法"},{"novel","adj. 新颖的 n. 小说"},
        {"objective","n. 目标 adj. 客观的"},{"oblige","v. 迫使；施恩于"},
        {"obscure","adj. 模糊的 v. 使朦胧"},{"obtain","v. 获得；取得"},
        {"occur","v. 发生；出现"},{"offset","v. 抵消 n. 补偿"},
        {"ongoing","adj. 持续的；进行中的"},{"optimize","v. 优化；充分利用"},
        {"orient","v. 使适应 n. 东方"},{"outline","n. 大纲 v. 概述"},
        {"output","n./v. 输出；产量"},{"overall","adj. 总体的；全面的"},
        {"overlap","v. 重叠 n. 重叠部分"},{"overwhelm","v. 压倒；淹没"},
        {"paradigm","n. 范式；范例"},{"paradox","n. 矛盾；悖论"},
        {"parameter","n. 参数；规范"},{"participate","v. 参与；参加"},
        {"perceive","v. 感知；察觉"},{"persist","v. 坚持；持续"},
        {"perspective","n. 视角；观点"},{"pertinent","adj. 相关的；恰当的"},
        {"phenomenon","n. 现象；奇迹"},{"philosophy","n. 哲学；人生观"},
        {"plausible","adj. 貌似合理的"},{"policy","n. 政策；保险单"},
        {"portray","v. 描绘；扮演"},{"potential","adj. 潜在的 n. 潜力"},
        {"precede","v. 在…之前；先于"},{"predominant","adj. 占优势的；主要的"},
        {"preliminary","adj. 初步的；预备的"},{"prescribe","v. 规定；开处方"},
        {"preserve","v. 保存；保护"},{"presumably","adv. 大概；可能"},
        {"prevail","v. 流行；占优势"},{"prevalent","adj. 普遍的；流行的"},
        {"primarily","adv. 主要地；根本地"},{"principal","adj. 主要的 n. 校长"},
        {"principle","n. 原则；原理"},{"prior","adj. 先前的；优先的"},
        {"priority","n. 优先；优先权"},{"probe","n./v. 探测；调查"},
        {"proceed","v. 继续；进行"},{"proclaim","v. 宣布；宣告"},
        {"profound","adj. 深刻的；深邃的"},{"prohibit","v. 禁止；阻止"},
        {"prominent","adj. 突出的；著名的"},{"promote","v. 促进；晋升"},
        {"prompt","v. 促使 adj. 迅速的"},{"proportion","n. 比例；部分"},
        {"propose","v. 建议；提议"},{"prospect","n. 前景；可能性"},
        {"protocol","n. 协议；礼仪"},{"provoke","v. 激怒；引起"},
        {"publish","v. 出版；发表"},{"pursue","v. 追求；追赶"},
        {"qualitative","adj. 定性的"},{"quantitative","adj. 定量的"},
        {"quest","n./v. 寻求；探索"},{"radical","adj. 激进的；根本的"},
        {"random","adj. 随机的；任意的"},{"rational","adj. 理性的；合理的"},
        {"readily","adv. 容易地；乐意地"},{"realm","n. 领域；范围"},
        {"reconcile","v. 调和；使和解"},{"refine","v. 精炼；提炼"},
        {"reflect","v. 反映；反射"},{"reform","n./v. 改革；改良"},
        {"regulate","v. 调节；管理"},{"reinforce","v. 加强；增强"},
        {"reject","v. 拒绝；排斥"},{"release","n./v. 释放；发布"},
        {"relevant","adj. 相关的；切题的"},{"reluctant","adj. 不情愿的"},
        {"render","v. 使成为；提供"},{"renowned","adj. 著名的；有名的"},
        {"replenish","v. 补充；再装满"},{"resemble","v. 像；类似"},
        {"resident","n. 居民 adj. 居住的"},{"resolve","v. 解决；决心"},
        {"restore","v. 恢复；修复"},{"restrain","v. 抑制；约束"},
        {"restrict","v. 限制；约束"},{"retain","v. 保持；保留"},
        {"retrieve","v. 取回；检索"},{"reveal","v. 揭示；透露"},
        {"revenue","n. 收入；税收"},{"reverse","v. 逆转 adj. 相反的"},
        {"revolution","n. 革命；变革"},{"rigorous","adj. 严格的；严密的"},
        {"robust","adj. 强健的；坚固的"},{"scheme","n. 计划；方案"},
        {"scope","n. 范围；领域"},{"scrutiny","n. 详细审查；细看"},
        {"segment","n. 部分；片段"},{"sequence","n. 顺序；序列"},
        {"shift","n./v. 转变；轮班"},{"significant","adj. 重要的；显著的"},
        {"simulate","v. 模拟；假装"},{"simultaneous","adj. 同时发生的"},
        {"sole","adj. 唯一的；单独的"},{"solicit","v. 恳求；招揽"},
        {"somewhat","adv. 稍微；有点"},{"sophisticated","adj. 复杂的；精致的"},
        {"specify","v. 指定；明确说明"},{"speculate","v. 推测；投机"},
        {"sphere","n. 领域；范围；球体"},{"spontaneous","adj. 自发的；自然的"},
        {"stable","adj. 稳定的 n. 马厩"},{"statistics","n. 统计学；统计数字"},
        {"status","n. 地位；状态"},{"stimulate","v. 刺激；激励"},
        {"straightforward","adj. 直截了当的"},{"strategy","n. 战略；策略"},
        {"stress","n. 压力 v. 强调"},{"structure","n. 结构 v. 构建"},
        {"subordinate","adj. 下级的 n. 下属"},{"subsequent","adj. 随后的；后来的"},
        {"subsidy","n. 补贴；津贴"},{"substantial","adj. 大量的；实质的"},
        {"substitute","n. 替代品 v. 替代"},{"sufficient","adj. 足够的；充分的"},
        {"summarize","v. 总结；概括"},{"superior","adj. 上级的；优越的"},
        {"supplement","n. 补充物 v. 补充"},{"surpass","v. 超越；胜过"},
        {"surplus","n. 盈余 adj. 过剩的"},{"survey","n./v. 调查；测量"},
        {"suspend","v. 暂停；悬挂"},{"sustain","v. 维持；支撑"},
        {"synthesis","n. 合成；综合"},{"systematic","adj. 系统的；有组织的"},
        {"tangible","adj. 有形的；可触摸的"},{"target","n. 目标 v. 瞄准"},
        {"temporary","adj. 临时的；暂时的"},{"terminate","v. 结束；终止"},
        {"thereby","adv. 因此；从而"},{"thesis","n. 论文；论题"},
        {"thorough","adj. 彻底的；周密的"},{"threshold","n. 门槛；界限"},
        {"trace","n. 痕迹 v. 追踪"},{"transform","v. 改变；转换"},
        {"transition","n. 过渡；转变"},{"trigger","n. 扳机 v. 触发"},
        {"ultimate","adj. 最终的；根本的"},{"undergo","v. 经历；遭受"},
        {"underlying","adj. 潜在的；根本的"},{"undermine","v. 破坏；削弱"},
        {"undertake","v. 承担；从事"},{"uniform","adj. 统一的 n. 制服"},
        {"unique","adj. 独特的；唯一的"},{"universal","adj. 普遍的；全体的"},
        {"utilize","v. 利用；使用"},{"valid","adj. 有效的；合理的"},
        {"vanish","v. 消失；突然不见"},{"variable","n. 变量 adj. 可变的"},
        {"vast","adj. 广阔的；巨大的"},{"versatile","adj. 多才多艺的；多功能的"},
        {"via","prep. 通过；经由"},{"virtual","adj. 虚拟的；实质上的"},
        {"visible","adj. 可见的；明显的"},{"vital","adj. 至关重要的"},
        {"volatile","adj. 不稳定的；易挥发的"},{"volume","n. 体积；音量"},
        {"voluntary","adj. 自愿的；志愿的"},{"vulnerable","adj. 脆弱的；易受伤的"},
        {"whereas","conj. 然而；鉴于"},{"widespread","adj. 广泛的；普遍的"},
        {"withstand","v. 承受；经受住"},{"yield","v. 产生 n. 产量"},
    };

    // ══════════════════ 生成方法 ══════════════════

    public static void main(String[] args) {
        System.out.println("=== 英语等级考试词库生成器 (扩展版) ===");
        ensureDir(SRC_DIR);
        ensureDir(WORK_DIR);

        generate(CET4, "CET4", 1);
        generate(CET6, "CET6", 2);
        generate(IELTS, "IELTS", 3);
        generate(TOEFL, "TOEFL", 4);

        System.out.println("\n词库生成完毕！总计: " + (CET4.length + CET6.length + IELTS.length + TOEFL.length) + " 词");
    }

    static void generate(String[][] words, String levelName, int levelValue) {
        System.out.println("\n生成 " + levelName + " ... " + words.length + " 词");
        writeLevelFile(new File(SRC_DIR + levelName + ".txt"), words, levelValue);
        writeLevelFile(new File(WORK_DIR + levelName + ".txt"), words, levelValue);
        System.out.println("  " + levelName + " 完成");
    }

    static void writeLevelFile(File file, String[][] words, int levelValue) {
        file.getParentFile().mkdirs();
        try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
            pw.println(words.length + "\t0");
            for (String[] w : words) {
                pw.println(w[0] + "\t" + w[1] + "\t1\t0\t0\t\t\t0\t" + levelValue);
            }
        } catch (Exception e) {
            System.err.println("写入失败: " + file.getAbsolutePath());
        }
    }

    static void ensureDir(String path) {
        File dir = new File(path);
        if (!dir.exists()) { dir.mkdirs(); }
    }
}
